package com.claystone.server.db;

// Generated 24 Feb, 2011 11:50:49 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;

import com.vividsolutions.jts.geom.Geometry;

/**
 * CompanyStationNew generated by hbm2java
 */
public class CompanyStationNew implements java.io.Serializable {

	private int stationId;
	private int companyId;
	private String stationName;
	private Geometry stationGeom;
	private String stationType;
	private int lastModifiedUser;
	private Date lastModifiedTime;
	private int recordStatus;
	private String stationCode;

	public CompanyStationNew() {
	}

	public CompanyStationNew(int stationId, int companyId, String stationName,
			String stationType, int lastModifiedUser, Date lastModifiedTime,
			int recordStatus) {
		this.stationId = stationId;
		this.companyId = companyId;
		this.stationName = stationName;
		this.stationType = stationType;
		this.lastModifiedUser = lastModifiedUser;
		this.lastModifiedTime = lastModifiedTime;
		this.recordStatus = recordStatus;
	}

	public CompanyStationNew(int stationId, int companyId, String stationName,
			Geometry stationGeom, String stationType, int lastModifiedUser,
			Date lastModifiedTime, int recordStatus) {
		this.stationId = stationId;
		this.companyId = companyId;
		this.stationName = stationName;
		this.stationGeom = stationGeom;
		this.stationType = stationType;
		this.lastModifiedUser = lastModifiedUser;
		this.lastModifiedTime = lastModifiedTime;
		this.recordStatus = recordStatus;
	}

	public int getStationId() {
		return this.stationId;
	}

	public void setStationId(int stationId) {
		this.stationId = stationId;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public String getStationName() {
		return this.stationName;
	}

	public void setStationName(String stationName) {
		this.stationName = stationName;
	}

	public Geometry getStationGeom() {
		return this.stationGeom;
	}

	public void setStationGeom(Geometry stationGeom) {
		this.stationGeom = stationGeom;
	}

	public String getStationType() {
		return this.stationType;
	}

	public void setStationType(String stationType) {
		this.stationType = stationType;
	}

	public int getLastModifiedUser() {
		return this.lastModifiedUser;
	}

	public void setLastModifiedUser(int lastModifiedUser) {
		this.lastModifiedUser = lastModifiedUser;
	}

	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	public int getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(int recordStatus) {
		this.recordStatus = recordStatus;
	}

	public String getStationCode() {
		return stationCode;
	}

	public void setStationCode(String stationCode) {
		this.stationCode = stationCode;
	}

}
