package com.claystone.server.db;

// Generated Jun 4, 2008 4:19:32 PM by Hibernate Tools 3.1.0.beta5

import java.util.Date;

import com.vividsolutions.jts.geom.Geometry;

/**
 * CompanyStation generated by hbm2java
 */
public class CompanyStation implements java.io.Serializable {

	// Fields    

	private int stationId;

	private int companyId;

	private String stationName;

	private Geometry stationGeom;

	private int stationRadiusMtr;

	private String stationType;

	private int lastModifiedUser;

	private Date lastModifiedTime;

	private int recordStatus;

	// Constructors

	/** default constructor */
	public CompanyStation() {
	}

	/** minimal constructor */
	public CompanyStation(int stationId, int companyId, String stationName,
			int stationRadiusMtr, String stationType, int lastModifiedUser,
			Date lastModifiedTime, int recordStatus) {
		this.stationId = stationId;
		this.companyId = companyId;
		this.stationName = stationName;
		this.stationRadiusMtr = stationRadiusMtr;
		this.stationType = stationType;
		this.lastModifiedUser = lastModifiedUser;
		this.lastModifiedTime = lastModifiedTime;
		this.recordStatus = recordStatus;
	}

	/** full constructor */
	public CompanyStation(int stationId, int companyId, String stationName,
			Geometry stationGeom, int stationRadiusMtr, String stationType,
			int lastModifiedUser, Date lastModifiedTime, int recordStatus) {
		this.stationId = stationId;
		this.companyId = companyId;
		this.stationName = stationName;
		this.stationGeom = stationGeom;
		this.stationRadiusMtr = stationRadiusMtr;
		this.stationType = stationType;
		this.lastModifiedUser = lastModifiedUser;
		this.lastModifiedTime = lastModifiedTime;
		this.recordStatus = recordStatus;
	}

	// Property accessors
	public int getStationId() {
		return this.stationId;
	}

	public void setStationId(int stationId) {
		this.stationId = stationId;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public String getStationName() {
		return this.stationName;
	}

	public void setStationName(String stationName) {
		this.stationName = stationName;
	}

	public Geometry getStationGeom() {
		return this.stationGeom;
	}

	public void setStationGeom(Geometry stationGeom) {
		this.stationGeom = stationGeom;
	}

	public int getStationRadiusMtr() {
		return this.stationRadiusMtr;
	}

	public void setStationRadiusMtr(int stationRadiusMtr) {
		this.stationRadiusMtr = stationRadiusMtr;
	}

	public String getStationType() {
		return this.stationType;
	}

	public void setStationType(String stationType) {
		this.stationType = stationType;
	}

	public int getLastModifiedUser() {
		return this.lastModifiedUser;
	}

	public void setLastModifiedUser(int lastModifiedUser) {
		this.lastModifiedUser = lastModifiedUser;
	}

	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	public int getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(int recordStatus) {
		this.recordStatus = recordStatus;
	}

}
