package com.claystone.server.db;

// Generated Jun 4, 2008 4:19:32 PM by Hibernate Tools 3.1.0.beta5

import java.util.Date;

import com.vividsolutions.jts.geom.Geometry;

/**
 * CompanyLocations generated by hbm2java
 */
public class CompanyLocations implements java.io.Serializable {

	// Fields    

	private int locId;

	private int companyId;

	private String locName;

	private Geometry locGeom;

	private int lastModifiedUser;

	private Date lastModifiedTime;

	private int recordStatus;

	// Constructors

	/** default constructor */
	public CompanyLocations() {
	}

	/** minimal constructor */
	public CompanyLocations(int locId, int companyId, String locName,
			int lastModifiedUser, Date lastModifiedTime, int recordStatus) {
		this.locId = locId;
		this.companyId = companyId;
		this.locName = locName;
		this.lastModifiedUser = lastModifiedUser;
		this.lastModifiedTime = lastModifiedTime;
		this.recordStatus = recordStatus;
	}

	/** full constructor */
	public CompanyLocations(int locId, int companyId, String locName,
			Geometry locGeom, int lastModifiedUser, Date lastModifiedTime,
			int recordStatus) {
		this.locId = locId;
		this.companyId = companyId;
		this.locName = locName;
		this.locGeom = locGeom;
		this.lastModifiedUser = lastModifiedUser;
		this.lastModifiedTime = lastModifiedTime;
		this.recordStatus = recordStatus;
	}

	// Property accessors
	public int getLocId() {
		return this.locId;
	}

	public void setLocId(int locId) {
		this.locId = locId;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public String getLocName() {
		return this.locName;
	}

	public void setLocName(String locName) {
		this.locName = locName;
	}

	public Geometry getLocGeom() {
		return this.locGeom;
	}

	public void setLocGeom(Geometry locGeom) {
		this.locGeom = locGeom;
	}

	public int getLastModifiedUser() {
		return this.lastModifiedUser;
	}

	public void setLastModifiedUser(int lastModifiedUser) {
		this.lastModifiedUser = lastModifiedUser;
	}

	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	public int getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(int recordStatus) {
		this.recordStatus = recordStatus;
	}

}
