package com.claystone.server.db;

// Generated Jun 4, 2008 4:19:32 PM by Hibernate Tools 3.1.0.beta5

import java.util.Date;

import com.vividsolutions.jts.geom.Geometry;

/**
 * CompanyRoutes generated by hbm2java
 */
public class CompanyRoutes implements java.io.Serializable {

	// Fields    

	private int routeId;

	private int companyId;

	private String routeName;

	private Geometry routeGeom;

	private int lastModifiedUser;

	private Date lastModifiedTime;

	private int recordStatus;

	// Constructors

	/** default constructor */
	public CompanyRoutes() {
	}

	/** minimal constructor */
	public CompanyRoutes(int routeId, int companyId, String routeName,
			int lastModifiedUser, Date lastModifiedTime, int recordStatus) {
		this.routeId = routeId;
		this.companyId = companyId;
		this.routeName = routeName;
		this.lastModifiedUser = lastModifiedUser;
		this.lastModifiedTime = lastModifiedTime;
		this.recordStatus = recordStatus;
	}

	/** full constructor */
	public CompanyRoutes(int routeId, int companyId, String routeName,
			Geometry routeGeom, int lastModifiedUser,
			Date lastModifiedTime, int recordStatus) {
		this.routeId = routeId;
		this.companyId = companyId;
		this.routeName = routeName;
		this.routeGeom = routeGeom;
		this.lastModifiedUser = lastModifiedUser;
		this.lastModifiedTime = lastModifiedTime;
		this.recordStatus = recordStatus;
	}

	// Property accessors
	public int getRouteId() {
		return this.routeId;
	}

	public void setRouteId(int routeId) {
		this.routeId = routeId;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public String getRouteName() {
		return this.routeName;
	}

	public void setRouteName(String routeName) {
		this.routeName = routeName;
	}

	public Geometry getRouteGeom() {
		return this.routeGeom;
	}

	public void setRouteGeom(Geometry routeGeom) {
		this.routeGeom = routeGeom;
	}

	public int getLastModifiedUser() {
		return this.lastModifiedUser;
	}

	public void setLastModifiedUser(int lastModifiedUser) {
		this.lastModifiedUser = lastModifiedUser;
	}

	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	public int getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(int recordStatus) {
		this.recordStatus = recordStatus;
	}

}
