UnitPoolSize=325
UnitMaxPoolSize=325
CompanyPoolSize=10
CompanyMaxPoolSize=10
KeepAliveTime=100
#bambooConnectionURL=jdbc:postgresql://10.9.112.3:5432/vTrack?user=postgres&password=Hashlogdbadm@2021
bambooConnectionURL=jdbc:postgresql://34.93.251.117:5432/vTrack?user=postgres&password=Hashlogdbadm@2021
dst=1
DatabaseName=vTrack
#ServerName=10.9.112.3
ServerName=34.93.251.117
User=postgres
Password=Hashlogdbadm@2021
MaxConnections=5
InitialConnections=1
PoolSizeDB=325
MaxPoolSizeDB=325
KeepAliveTimeDB=100
BambooPoolSize=1
BambooMaxPoolSize=5
BambooKeepAliveTime=100
PortNumber=5432
Logging=1
UnitCompanyIds=387,399,403,393,394,386,163
UnitProviderIds=1,2,5,10,14,94,127,131,123,124,67,76,16,17,25,26,52,53,96,97,50,121,147,148,149,150,151,152,156,157,158,159,160,161,165,164,167,168,169,162,172,173,174,175,177,178,179,180,183,184,188
CompCompanyIds=399,387,403,393,394,424,406,163
CompProviderIds=85,6,58,132,135,138,60,61,155,163,176,181,182,185
UnitEFCONCompanyIds=399
UnitEFCONProviderIds=32
EFKONStartAPI=http://efkonsuzuki.com:1098/api/track/transStart
EFKONStopAPI=http://efkonsuzuki.com:1098/api/track/transStop
EFKONRequestParams=username=EfkonTransystems&password=EFKTLI@123&vehicles=
UnitTrimbleCompanyIds=399
UnitTrimbleProviderIds=103
TrimbleStartAPI=https://ws.tmsitrimble.in/Services/tracking/startTrack
TrimbleStopAPI=https://ws.tmsitrimble.in/Services/tracking/stopTrack
EnMovilCompanyIds=399
EnMovilProviderIds=153
EnMovilStartAPI=http://enmovil.io/haka/api/subscribeVehicles
EnMovilStopAPI=http://enmovil.io/haka/api/unsubscribeVehicles
EnMovilLoginUrl=http://enmovil.io/haka/api/login
EnMovilUsrName=hashlogTrans
EnMovilPwd=hashTrans321
EnMovilEmailID=admin@hashlog.in
EnMovilKeyValue=TransSystems
SAMRXTokenURL=https://app.locate365.in/api/v1/motherson/authentication
SAMRXClientKey=adsfaser678ds211dffdgdfg23122:tyudfxefv234fd4fytfbweeveewc
SAMRXVehicleURL=https://app.locate365.in/api/v1/motherson/vehicle/live
AticUnitCompanyIds=387,393,394,399,403
AticUnitProviderIds=203,204
tokenAticURL =https://login.mzoneweb.net/connect/token
aticClientID=mz-aticapi
aticClientSecret=Lj4f6NHn.Tz6#KycUgsvEMiL
aticGrantType=password
aticUserName=tliadmin
aticPassword=tliadmin
aticMasterURL=https://live.mzoneweb.net/mzone62.api/Vehicles?&$select=id,description,unit_Description
TATAMOTOR-VEHICLE_LIMIT=25
FleetRadarCompanyIds=399
FleetRadarProviderIds=212
FastTagUnitPoolSize=5
FastTagUnitMaxPoolSize=5
FastTagCompanyIds=462,463
FastTagProviderIds=222,223
#polling_hours=24
polling_hours=10