package com.claystone.db;
// Generated 21 Dec, 2021 9:23:46 PM by Hibernate Tools 3.5.0.Final

/**
 * CanbusVehicleParamsId generated by hbm2java
 */
public class CanbusVehicleParamsId implements java.io.Serializable {

	private int companyId;
	private int vehicleId;
	private String ztVarId;
	private String canVarId;

	public CanbusVehicleParamsId() {
	}

	public CanbusVehicleParamsId(int companyId, int vehicleId, String ztVarId, String canVarId) {
		this.companyId = companyId;
		this.vehicleId = vehicleId;
		this.ztVarId = ztVarId;
		this.canVarId = canVarId;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public int getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(int vehicleId) {
		this.vehicleId = vehicleId;
	}

	public String getZtVarId() {
		return this.ztVarId;
	}

	public void setZtVarId(String ztVarId) {
		this.ztVarId = ztVarId;
	}

	public String getCanVarId() {
		return this.canVarId;
	}

	public void setCanVarId(String canVarId) {
		this.canVarId = canVarId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CanbusVehicleParamsId))
			return false;
		CanbusVehicleParamsId castOther = (CanbusVehicleParamsId) other;

		return (this.getCompanyId() == castOther.getCompanyId()) && (this.getVehicleId() == castOther.getVehicleId())
				&& ((this.getZtVarId() == castOther.getZtVarId()) || (this.getZtVarId() != null
						&& castOther.getZtVarId() != null && this.getZtVarId().equals(castOther.getZtVarId())))
				&& ((this.getCanVarId() == castOther.getCanVarId()) || (this.getCanVarId() != null
						&& castOther.getCanVarId() != null && this.getCanVarId().equals(castOther.getCanVarId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCompanyId();
		result = 37 * result + this.getVehicleId();
		result = 37 * result + (getZtVarId() == null ? 0 : this.getZtVarId().hashCode());
		result = 37 * result + (getCanVarId() == null ? 0 : this.getCanVarId().hashCode());
		return result;
	}

}
