package com.claystone.db;
// Generated 21 Dec, 2021 9:23:46 PM by Hibernate Tools 3.5.0.Final

/**
 * CanbusVehicleParams generated by hbm2java
 */
public class CanbusVehicleParams implements java.io.Serializable {

	private CanbusVehicleParamsId id;
	private boolean canVarStatus;

	public CanbusVehicleParams() {
	}

	public CanbusVehicleParams(CanbusVehicleParamsId id, boolean canVarStatus) {
		this.id = id;
		this.canVarStatus = canVarStatus;
	}

	public CanbusVehicleParamsId getId() {
		return this.id;
	}

	public void setId(CanbusVehicleParamsId id) {
		this.id = id;
	}

	public boolean isCanVarStatus() {
		return this.canVarStatus;
	}

	public void setCanVarStatus(boolean canVarStatus) {
		this.canVarStatus = canVarStatus;
	}

}
