package com.claystone.db;
// Generated 21 Dec, 2021 9:23:46 PM by Hibernate Tools 3.5.0.Final

/**
 * CanbusGpsdata generated by hbm2java
 */
public class CanbusGpsdata implements java.io.Serializable {

	private CanbusGpsdataId id;
	private String output1;
	private String output2;
	private String output3;
	private String output4;
	private String output5;
	private String output6;
	private String output7;
	private String output8;
	private String output9;
	private String output10;
	private String output11;
	private String output12;
	private String output13;
	private String output14;
	private String output15;
	private String output16;
	private String output17;
	private String output18;
	private String output19;
	private String output20;
	private String output21;
	private String output22;
	private String output23;
	private String output24;
	private String output25;
	private String output26;
	private String output27;
	private String output28;
	private String output29;
	private String output30;
	private String output31;
	private String output32;
	private String output33;
	private String output34;
	private String output35;
	private String output36;
	private String output37;
	private String output38;
	private String output39;
	private String output40;
	private String output41;
	private String output42;
	private String output43;
	private String output44;
	private String output45;
	private String output46;
	private String output47;
	private String output48;
	private String output49;
	private String output50;
	private String output51;
	private String output52;
	private String output53;
	private String output54;
	private String output55;
	private String output56;
	private String output57;
	private String output58;
	private String output59;
	private String output60;
	private String output61;
	private String output62;
	private String output63;
	private String reserve;
	private boolean processedFlag;

	public CanbusGpsdata() {
	}

	public CanbusGpsdata(CanbusGpsdataId id, boolean processedFlag) {
		this.id = id;
		this.processedFlag = processedFlag;
	}

	public CanbusGpsdata(CanbusGpsdataId id, String output1, String output2, String output3, String output4,
			String output5, String output6, String output7, String output8, String output9, String output10,
			String output11, String output12, String output13, String output14, String output15, String output16,
			String output17, String output18, String output19, String output20, String output21, String output22,
			String output23, String output24, String output25, String output26, String output27, String output28,
			String output29, String output30, String output31, String output32, String output33, String output34,
			String output35, String output36, String output37, String output38, String output39, String output40,
			String output41, String output42, String output43, String output44, String output45, String output46,
			String output47, String output48, String output49, String output50, String output51, String output52,
			String output53, String output54, String output55, String output56, String output57, String output58,
			String output59, String output60, String output61, String output62, String output63, String reserve,
			boolean processedFlag) {
		this.id = id;
		this.output1 = output1;
		this.output2 = output2;
		this.output3 = output3;
		this.output4 = output4;
		this.output5 = output5;
		this.output6 = output6;
		this.output7 = output7;
		this.output8 = output8;
		this.output9 = output9;
		this.output10 = output10;
		this.output11 = output11;
		this.output12 = output12;
		this.output13 = output13;
		this.output14 = output14;
		this.output15 = output15;
		this.output16 = output16;
		this.output17 = output17;
		this.output18 = output18;
		this.output19 = output19;
		this.output20 = output20;
		this.output21 = output21;
		this.output22 = output22;
		this.output23 = output23;
		this.output24 = output24;
		this.output25 = output25;
		this.output26 = output26;
		this.output27 = output27;
		this.output28 = output28;
		this.output29 = output29;
		this.output30 = output30;
		this.output31 = output31;
		this.output32 = output32;
		this.output33 = output33;
		this.output34 = output34;
		this.output35 = output35;
		this.output36 = output36;
		this.output37 = output37;
		this.output38 = output38;
		this.output39 = output39;
		this.output40 = output40;
		this.output41 = output41;
		this.output42 = output42;
		this.output43 = output43;
		this.output44 = output44;
		this.output45 = output45;
		this.output46 = output46;
		this.output47 = output47;
		this.output48 = output48;
		this.output49 = output49;
		this.output50 = output50;
		this.output51 = output51;
		this.output52 = output52;
		this.output53 = output53;
		this.output54 = output54;
		this.output55 = output55;
		this.output56 = output56;
		this.output57 = output57;
		this.output58 = output58;
		this.output59 = output59;
		this.output60 = output60;
		this.output61 = output61;
		this.output62 = output62;
		this.output63 = output63;
		this.reserve = reserve;
		this.processedFlag = processedFlag;
	}

	public CanbusGpsdataId getId() {
		return this.id;
	}

	public void setId(CanbusGpsdataId id) {
		this.id = id;
	}

	public String getOutput1() {
		return this.output1;
	}

	public void setOutput1(String output1) {
		this.output1 = output1;
	}

	public String getOutput2() {
		return this.output2;
	}

	public void setOutput2(String output2) {
		this.output2 = output2;
	}

	public String getOutput3() {
		return this.output3;
	}

	public void setOutput3(String output3) {
		this.output3 = output3;
	}

	public String getOutput4() {
		return this.output4;
	}

	public void setOutput4(String output4) {
		this.output4 = output4;
	}

	public String getOutput5() {
		return this.output5;
	}

	public void setOutput5(String output5) {
		this.output5 = output5;
	}

	public String getOutput6() {
		return this.output6;
	}

	public void setOutput6(String output6) {
		this.output6 = output6;
	}

	public String getOutput7() {
		return this.output7;
	}

	public void setOutput7(String output7) {
		this.output7 = output7;
	}

	public String getOutput8() {
		return this.output8;
	}

	public void setOutput8(String output8) {
		this.output8 = output8;
	}

	public String getOutput9() {
		return this.output9;
	}

	public void setOutput9(String output9) {
		this.output9 = output9;
	}

	public String getOutput10() {
		return this.output10;
	}

	public void setOutput10(String output10) {
		this.output10 = output10;
	}

	public String getOutput11() {
		return this.output11;
	}

	public void setOutput11(String output11) {
		this.output11 = output11;
	}

	public String getOutput12() {
		return this.output12;
	}

	public void setOutput12(String output12) {
		this.output12 = output12;
	}

	public String getOutput13() {
		return this.output13;
	}

	public void setOutput13(String output13) {
		this.output13 = output13;
	}

	public String getOutput14() {
		return this.output14;
	}

	public void setOutput14(String output14) {
		this.output14 = output14;
	}

	public String getOutput15() {
		return this.output15;
	}

	public void setOutput15(String output15) {
		this.output15 = output15;
	}

	public String getOutput16() {
		return this.output16;
	}

	public void setOutput16(String output16) {
		this.output16 = output16;
	}

	public String getOutput17() {
		return this.output17;
	}

	public void setOutput17(String output17) {
		this.output17 = output17;
	}

	public String getOutput18() {
		return this.output18;
	}

	public void setOutput18(String output18) {
		this.output18 = output18;
	}

	public String getOutput19() {
		return this.output19;
	}

	public void setOutput19(String output19) {
		this.output19 = output19;
	}

	public String getOutput20() {
		return this.output20;
	}

	public void setOutput20(String output20) {
		this.output20 = output20;
	}

	public String getOutput21() {
		return this.output21;
	}

	public void setOutput21(String output21) {
		this.output21 = output21;
	}

	public String getOutput22() {
		return this.output22;
	}

	public void setOutput22(String output22) {
		this.output22 = output22;
	}

	public String getOutput23() {
		return this.output23;
	}

	public void setOutput23(String output23) {
		this.output23 = output23;
	}

	public String getOutput24() {
		return this.output24;
	}

	public void setOutput24(String output24) {
		this.output24 = output24;
	}

	public String getOutput25() {
		return this.output25;
	}

	public void setOutput25(String output25) {
		this.output25 = output25;
	}

	public String getOutput26() {
		return this.output26;
	}

	public void setOutput26(String output26) {
		this.output26 = output26;
	}

	public String getOutput27() {
		return this.output27;
	}

	public void setOutput27(String output27) {
		this.output27 = output27;
	}

	public String getOutput28() {
		return this.output28;
	}

	public void setOutput28(String output28) {
		this.output28 = output28;
	}

	public String getOutput29() {
		return this.output29;
	}

	public void setOutput29(String output29) {
		this.output29 = output29;
	}

	public String getOutput30() {
		return this.output30;
	}

	public void setOutput30(String output30) {
		this.output30 = output30;
	}

	public String getOutput31() {
		return this.output31;
	}

	public void setOutput31(String output31) {
		this.output31 = output31;
	}

	public String getOutput32() {
		return this.output32;
	}

	public void setOutput32(String output32) {
		this.output32 = output32;
	}

	public String getOutput33() {
		return this.output33;
	}

	public void setOutput33(String output33) {
		this.output33 = output33;
	}

	public String getOutput34() {
		return this.output34;
	}

	public void setOutput34(String output34) {
		this.output34 = output34;
	}

	public String getOutput35() {
		return this.output35;
	}

	public void setOutput35(String output35) {
		this.output35 = output35;
	}

	public String getOutput36() {
		return this.output36;
	}

	public void setOutput36(String output36) {
		this.output36 = output36;
	}

	public String getOutput37() {
		return this.output37;
	}

	public void setOutput37(String output37) {
		this.output37 = output37;
	}

	public String getOutput38() {
		return this.output38;
	}

	public void setOutput38(String output38) {
		this.output38 = output38;
	}

	public String getOutput39() {
		return this.output39;
	}

	public void setOutput39(String output39) {
		this.output39 = output39;
	}

	public String getOutput40() {
		return this.output40;
	}

	public void setOutput40(String output40) {
		this.output40 = output40;
	}

	public String getOutput41() {
		return this.output41;
	}

	public void setOutput41(String output41) {
		this.output41 = output41;
	}

	public String getOutput42() {
		return this.output42;
	}

	public void setOutput42(String output42) {
		this.output42 = output42;
	}

	public String getOutput43() {
		return this.output43;
	}

	public void setOutput43(String output43) {
		this.output43 = output43;
	}

	public String getOutput44() {
		return this.output44;
	}

	public void setOutput44(String output44) {
		this.output44 = output44;
	}

	public String getOutput45() {
		return this.output45;
	}

	public void setOutput45(String output45) {
		this.output45 = output45;
	}

	public String getOutput46() {
		return this.output46;
	}

	public void setOutput46(String output46) {
		this.output46 = output46;
	}

	public String getOutput47() {
		return this.output47;
	}

	public void setOutput47(String output47) {
		this.output47 = output47;
	}

	public String getOutput48() {
		return this.output48;
	}

	public void setOutput48(String output48) {
		this.output48 = output48;
	}

	public String getOutput49() {
		return this.output49;
	}

	public void setOutput49(String output49) {
		this.output49 = output49;
	}

	public String getOutput50() {
		return this.output50;
	}

	public void setOutput50(String output50) {
		this.output50 = output50;
	}

	public String getOutput51() {
		return this.output51;
	}

	public void setOutput51(String output51) {
		this.output51 = output51;
	}

	public String getOutput52() {
		return this.output52;
	}

	public void setOutput52(String output52) {
		this.output52 = output52;
	}

	public String getOutput53() {
		return this.output53;
	}

	public void setOutput53(String output53) {
		this.output53 = output53;
	}

	public String getOutput54() {
		return this.output54;
	}

	public void setOutput54(String output54) {
		this.output54 = output54;
	}

	public String getOutput55() {
		return this.output55;
	}

	public void setOutput55(String output55) {
		this.output55 = output55;
	}

	public String getOutput56() {
		return this.output56;
	}

	public void setOutput56(String output56) {
		this.output56 = output56;
	}

	public String getOutput57() {
		return this.output57;
	}

	public void setOutput57(String output57) {
		this.output57 = output57;
	}

	public String getOutput58() {
		return this.output58;
	}

	public void setOutput58(String output58) {
		this.output58 = output58;
	}

	public String getOutput59() {
		return this.output59;
	}

	public void setOutput59(String output59) {
		this.output59 = output59;
	}

	public String getOutput60() {
		return this.output60;
	}

	public void setOutput60(String output60) {
		this.output60 = output60;
	}

	public String getOutput61() {
		return this.output61;
	}

	public void setOutput61(String output61) {
		this.output61 = output61;
	}

	public String getOutput62() {
		return this.output62;
	}

	public void setOutput62(String output62) {
		this.output62 = output62;
	}

	public String getOutput63() {
		return this.output63;
	}

	public void setOutput63(String output63) {
		this.output63 = output63;
	}

	public String getReserve() {
		return this.reserve;
	}

	public void setReserve(String reserve) {
		this.reserve = reserve;
	}

	public boolean isProcessedFlag() {
		return this.processedFlag;
	}

	public void setProcessedFlag(boolean processedFlag) {
		this.processedFlag = processedFlag;
	}

}
