package com.claystone.db;
// Generated Feb 28, 2020 10:27:13 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {

	private int companyId;
	private String companyCodeName;
	private String companyName;
	private String companyNameNative;
	private Date lastModifiedTime;
	private String lastModifiedUser;
	private int companyTypeId;
	private short companyAccessLevel;
	private String companyLogonUrl;
	private String companyLogoffUrl;
	private String companyAddress;
	private String companyLogo;
	private String companyUrl;
	private int companyType;
	private String companyCode;
	private String groupOwnerId;
	private String contactPerson;
	private String contactNumber1;
	private String contactNumber2;
	private String gpsDeviceType;
	private String driverAppFeature;
	private String groupCompany;
	private String excludeSubGroups;
	private String excludeGroupCompany;

	public Company() {
	}

	public Company(int companyId, String companyCodeName, String companyName, Date lastModifiedTime,
			String lastModifiedUser, int companyTypeId, short companyAccessLevel, String companyLogonUrl,
			String companyLogoffUrl, int companyType) {
		this.companyId = companyId;
		this.companyCodeName = companyCodeName;
		this.companyName = companyName;
		this.lastModifiedTime = lastModifiedTime;
		this.lastModifiedUser = lastModifiedUser;
		this.companyTypeId = companyTypeId;
		this.companyAccessLevel = companyAccessLevel;
		this.companyLogonUrl = companyLogonUrl;
		this.companyLogoffUrl = companyLogoffUrl;
		this.companyType = companyType;
	}

	public Company(int companyId, String companyCodeName, String companyName, String companyNameNative,
			Date lastModifiedTime, String lastModifiedUser, int companyTypeId, short companyAccessLevel,
			String companyLogonUrl, String companyLogoffUrl, String companyAddress, String companyLogo,
			String companyUrl, int companyType, String companyCode, String groupOwnerId, String contactPerson,
			String contactNumber1, String contactNumber2, String gpsDeviceType, String driverAppFeature,
			String groupCompany) {
		this.companyId = companyId;
		this.companyCodeName = companyCodeName;
		this.companyName = companyName;
		this.companyNameNative = companyNameNative;
		this.lastModifiedTime = lastModifiedTime;
		this.lastModifiedUser = lastModifiedUser;
		this.companyTypeId = companyTypeId;
		this.companyAccessLevel = companyAccessLevel;
		this.companyLogonUrl = companyLogonUrl;
		this.companyLogoffUrl = companyLogoffUrl;
		this.companyAddress = companyAddress;
		this.companyLogo = companyLogo;
		this.companyUrl = companyUrl;
		this.companyType = companyType;
		this.companyCode = companyCode;
		this.groupOwnerId = groupOwnerId;
		this.contactPerson = contactPerson;
		this.contactNumber1 = contactNumber1;
		this.contactNumber2 = contactNumber2;
		this.gpsDeviceType = gpsDeviceType;
		this.driverAppFeature = driverAppFeature;
		this.groupCompany = groupCompany;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public String getCompanyCodeName() {
		return this.companyCodeName;
	}

	public void setCompanyCodeName(String companyCodeName) {
		this.companyCodeName = companyCodeName;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getCompanyNameNative() {
		return this.companyNameNative;
	}

	public void setCompanyNameNative(String companyNameNative) {
		this.companyNameNative = companyNameNative;
	}

	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	public String getLastModifiedUser() {
		return this.lastModifiedUser;
	}

	public void setLastModifiedUser(String lastModifiedUser) {
		this.lastModifiedUser = lastModifiedUser;
	}

	public int getCompanyTypeId() {
		return this.companyTypeId;
	}

	public void setCompanyTypeId(int companyTypeId) {
		this.companyTypeId = companyTypeId;
	}

	public short getCompanyAccessLevel() {
		return this.companyAccessLevel;
	}

	public void setCompanyAccessLevel(short companyAccessLevel) {
		this.companyAccessLevel = companyAccessLevel;
	}

	public String getCompanyLogonUrl() {
		return this.companyLogonUrl;
	}

	public void setCompanyLogonUrl(String companyLogonUrl) {
		this.companyLogonUrl = companyLogonUrl;
	}

	public String getCompanyLogoffUrl() {
		return this.companyLogoffUrl;
	}

	public void setCompanyLogoffUrl(String companyLogoffUrl) {
		this.companyLogoffUrl = companyLogoffUrl;
	}

	public String getCompanyAddress() {
		return this.companyAddress;
	}

	public void setCompanyAddress(String companyAddress) {
		this.companyAddress = companyAddress;
	}

	public String getCompanyLogo() {
		return this.companyLogo;
	}

	public void setCompanyLogo(String companyLogo) {
		this.companyLogo = companyLogo;
	}

	public String getCompanyUrl() {
		return this.companyUrl;
	}

	public void setCompanyUrl(String companyUrl) {
		this.companyUrl = companyUrl;
	}

	public int getCompanyType() {
		return this.companyType;
	}

	public void setCompanyType(int companyType) {
		this.companyType = companyType;
	}

	public String getCompanyCode() {
		return this.companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	public String getGroupOwnerId() {
		return this.groupOwnerId;
	}

	public void setGroupOwnerId(String groupOwnerId) {
		this.groupOwnerId = groupOwnerId;
	}

	public String getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	public String getContactNumber1() {
		return this.contactNumber1;
	}

	public void setContactNumber1(String contactNumber1) {
		this.contactNumber1 = contactNumber1;
	}

	public String getContactNumber2() {
		return this.contactNumber2;
	}

	public void setContactNumber2(String contactNumber2) {
		this.contactNumber2 = contactNumber2;
	}

	public String getGpsDeviceType() {
		return this.gpsDeviceType;
	}

	public void setGpsDeviceType(String gpsDeviceType) {
		this.gpsDeviceType = gpsDeviceType;
	}

	public String getDriverAppFeature() {
		return this.driverAppFeature;
	}

	public void setDriverAppFeature(String driverAppFeature) {
		this.driverAppFeature = driverAppFeature;
	}

	public String getGroupCompany() {
		return this.groupCompany;
	}

	public void setGroupCompany(String groupCompany) {
		this.groupCompany = groupCompany;
	}

	public String getExcludeSubGroups() {
		return excludeSubGroups;
	}

	public void setExcludeSubGroups(String excludeSubGroups) {
		this.excludeSubGroups = excludeSubGroups;
	}

	public String getExcludeGroupCompany() {
		return excludeGroupCompany;
	}

	public void setExcludeGroupCompany(String excludeGroupCompany) {
		this.excludeGroupCompany = excludeGroupCompany;
	}

}
