package com.claystone.db;
// Generated Feb 28, 2020 4:45:30 PM by Hibernate Tools 3.5.0.Final

/**
 * DataProviderId generated by hbm2java
 */
public class DataProviderId implements java.io.Serializable {

	private int dataProviderId;
	private String dataProviderName;

	public DataProviderId() {
	}

	public DataProviderId(int dataProviderId, String dataProviderName) {
		this.dataProviderId = dataProviderId;
		this.dataProviderName = dataProviderName;
	}

	public int getDataProviderId() {
		return this.dataProviderId;
	}

	public void setDataProviderId(int dataProviderId) {
		this.dataProviderId = dataProviderId;
	}

	public String getDataProviderName() {
		return this.dataProviderName;
	}

	public void setDataProviderName(String dataProviderName) {
		this.dataProviderName = dataProviderName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DataProviderId))
			return false;
		DataProviderId castOther = (DataProviderId) other;

		return (this.getDataProviderId() == castOther.getDataProviderId())
				&& ((this.getDataProviderName() == castOther.getDataProviderName())
						|| (this.getDataProviderName() != null && castOther.getDataProviderName() != null
								&& this.getDataProviderName().equals(castOther.getDataProviderName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDataProviderId();
		result = 37 * result + (getDataProviderName() == null ? 0 : this.getDataProviderName().hashCode());
		return result;
	}

}
