package com.claystone.db;
// Generated Feb 28, 2020 4:45:30 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * DataProvider generated by hbm2java
 */
public class DataProvider implements java.io.Serializable {

	private DataProviderId id;
	private int companyId;
	private String tokenUrl;
	private String apiUrl;
	private String tokenReqParams;
	private String apiReqParams;
	private String tokenReqMethod;
	private String apiReqMethod;
	private String tokenResType;
	private String apiResType;
	private int dataInterval;
	private int recordStatus;
	private int lastModifiedUser;
	private Date lasModifiedTime;
	private String unitPrefix;
	private int unitSeq;
	private String searchKey;
	private Boolean isTokenEnable;
	private Date nextProcessedTime;
	

	public DataProvider() {
	}

	public DataProvider(DataProviderId id, int companyId, String tokenUrl, String apiUrl, String tokenReqParams,
			String apiReqParams, String tokenReqMethod, String apiReqMethod, String tokenResType, String apiResType,
			int dataInterval, int recordStatus, int lastModifiedUser, Date lasModifiedTime, String unitPrefix,
			int unitSeq,Date nextProcessedTime) {
		this.id = id;
		this.companyId = companyId;
		this.tokenUrl = tokenUrl;
		this.apiUrl = apiUrl;
		this.tokenReqParams = tokenReqParams;
		this.apiReqParams = apiReqParams;
		this.tokenReqMethod = tokenReqMethod;
		this.apiReqMethod = apiReqMethod;
		this.tokenResType = tokenResType;
		this.apiResType = apiResType;
		this.dataInterval = dataInterval;
		this.recordStatus = recordStatus;
		this.lastModifiedUser = lastModifiedUser;
		this.lasModifiedTime = lasModifiedTime;
		this.unitPrefix = unitPrefix;
		this.unitSeq = unitSeq;
		this.nextProcessedTime = nextProcessedTime;
	}

	public DataProviderId getId() {
		return this.id;
	}

	public void setId(DataProviderId id) {
		this.id = id;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public String getTokenUrl() {
		return this.tokenUrl;
	}

	public void setTokenUrl(String tokenUrl) {
		this.tokenUrl = tokenUrl;
	}

	public String getApiUrl() {
		return this.apiUrl;
	}

	public void setApiUrl(String apiUrl) {
		this.apiUrl = apiUrl;
	}

	public String getTokenReqParams() {
		return this.tokenReqParams;
	}

	public void setTokenReqParams(String tokenReqParams) {
		this.tokenReqParams = tokenReqParams;
	}

	public String getApiReqParams() {
		return this.apiReqParams;
	}

	public void setApiReqParams(String apiReqParams) {
		this.apiReqParams = apiReqParams;
	}

	public String getTokenReqMethod() {
		return this.tokenReqMethod;
	}

	public void setTokenReqMethod(String tokenReqMethod) {
		this.tokenReqMethod = tokenReqMethod;
	}

	public String getApiReqMethod() {
		return this.apiReqMethod;
	}

	public void setApiReqMethod(String apiReqMethod) {
		this.apiReqMethod = apiReqMethod;
	}

	public String getTokenResType() {
		return this.tokenResType;
	}

	public void setTokenResType(String tokenResType) {
		this.tokenResType = tokenResType;
	}

	public String getApiResType() {
		return this.apiResType;
	}

	public void setApiResType(String apiResType) {
		this.apiResType = apiResType;
	}

	public int getDataInterval() {
		return this.dataInterval;
	}

	public void setDataInterval(int dataInterval) {
		this.dataInterval = dataInterval;
	}

	public int getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(int recordStatus) {
		this.recordStatus = recordStatus;
	}

	public int getLastModifiedUser() {
		return this.lastModifiedUser;
	}

	public void setLastModifiedUser(int lastModifiedUser) {
		this.lastModifiedUser = lastModifiedUser;
	}

	public Date getLasModifiedTime() {
		return this.lasModifiedTime;
	}

	public void setLasModifiedTime(Date lasModifiedTime) {
		this.lasModifiedTime = lasModifiedTime;
	}

	public String getUnitPrefix() {
		return this.unitPrefix;
	}

	public void setUnitPrefix(String unitPrefix) {
		this.unitPrefix = unitPrefix;
	}

	public int getUnitSeq() {
		return this.unitSeq;
	}

	public void setUnitSeq(int unitSeq) {
		this.unitSeq = unitSeq;
	}

	public String getSearchKey() {
		return searchKey;
	}

	public void setSearchKey(String searchKey) {
		this.searchKey = searchKey;
	}

	public Boolean getIsTokenEnable() {
		return isTokenEnable;
	}

	public void setIsTokenEnable(Boolean isTokenEnable) {
		this.isTokenEnable = isTokenEnable;
	}

	public Date getNextProcessedTime() {
		return nextProcessedTime;
	}

	public void setNextProcessedTime(Date nextProcessedTime) {
		this.nextProcessedTime = nextProcessedTime;
	}

	
}
