package com.claystone.db;
// Generated Feb 28, 2020 4:45:30 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * DeviceType generated by hbm2java
 */
public class DeviceType implements java.io.Serializable {

	private DeviceTypeId id;
	private int recordStatus;
	private int lastModifiedUser;
	private Date lasModifiedTime;

	public DeviceType() {
	}

	public DeviceType(DeviceTypeId id, int recordStatus, int lastModifiedUser, Date lasModifiedTime) {
		this.id = id;
		this.recordStatus = recordStatus;
		this.lastModifiedUser = lastModifiedUser;
		this.lasModifiedTime = lasModifiedTime;
	}

	public DeviceTypeId getId() {
		return this.id;
	}

	public void setId(DeviceTypeId id) {
		this.id = id;
	}

	public int getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(int recordStatus) {
		this.recordStatus = recordStatus;
	}

	public int getLastModifiedUser() {
		return this.lastModifiedUser;
	}

	public void setLastModifiedUser(int lastModifiedUser) {
		this.lastModifiedUser = lastModifiedUser;
	}

	public Date getLasModifiedTime() {
		return this.lasModifiedTime;
	}

	public void setLasModifiedTime(Date lasModifiedTime) {
		this.lasModifiedTime = lasModifiedTime;
	}

}
