package com.claystone.db;
// Generated Feb 28, 2020 4:45:30 PM by Hibernate Tools 3.5.0.Final

/**
 * DeviceTypeId generated by hbm2java
 */
public class DeviceTypeId implements java.io.Serializable {

	private int hardwareId;
	private String hardwareName;

	public DeviceTypeId() {
	}

	public DeviceTypeId(int hardwareId, String hardwareName) {
		this.hardwareId = hardwareId;
		this.hardwareName = hardwareName;
	}

	public int getHardwareId() {
		return this.hardwareId;
	}

	public void setHardwareId(int hardwareId) {
		this.hardwareId = hardwareId;
	}

	public String getHardwareName() {
		return this.hardwareName;
	}

	public void setHardwareName(String hardwareName) {
		this.hardwareName = hardwareName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DeviceTypeId))
			return false;
		DeviceTypeId castOther = (DeviceTypeId) other;

		return (this.getHardwareId() == castOther.getHardwareId())
				&& ((this.getHardwareName() == castOther.getHardwareName())
						|| (this.getHardwareName() != null && castOther.getHardwareName() != null
								&& this.getHardwareName().equals(castOther.getHardwareName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getHardwareId();
		result = 37 * result + (getHardwareName() == null ? 0 : this.getHardwareName().hashCode());
		return result;
	}

}
