package com.claystone.db;
// Generated 4 Jun, 2010 12:56:15 PM by Hibernate Tools 3.2.4.GA

/**
 * Driver generated by hbm2java
 */
public class Driver implements java.io.Serializable {

	private int driverId;
	private int companyId;
	private String firstName;
	private String middleName;
	private String lastName;
	private String licenseNumber;
	private String phoneNumber;
	private String mobileNumber;
	private String idCardNumber;
	private String driverPhotoUrl;
	private String address;
	private short recordStatus;

	public Driver() {
	}

	public Driver(int driverId, int companyId, String firstName,
			String licenseNumber, short recordStatus) {
		this.driverId = driverId;
		this.companyId = companyId;
		this.firstName = firstName;
		this.licenseNumber = licenseNumber;
		this.recordStatus = recordStatus;
	}

	public Driver(int driverId, int companyId, String firstName,
			String middleName, String lastName, String licenseNumber,
			String phoneNumber, String mobileNumber, String idCardNumber,
			String driverPhotoUrl, String address, short recordStatus) {
		this.driverId = driverId;
		this.companyId = companyId;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.licenseNumber = licenseNumber;
		this.phoneNumber = phoneNumber;
		this.mobileNumber = mobileNumber;
		this.idCardNumber = idCardNumber;
		this.driverPhotoUrl = driverPhotoUrl;
		this.address = address;
		this.recordStatus = recordStatus;
	}

	public int getDriverId() {
		return this.driverId;
	}

	public void setDriverId(int driverId) {
		this.driverId = driverId;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getLicenseNumber() {
		return this.licenseNumber;
	}

	public void setLicenseNumber(String licenseNumber) {
		this.licenseNumber = licenseNumber;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	public String getIdCardNumber() {
		return this.idCardNumber;
	}

	public void setIdCardNumber(String idCardNumber) {
		this.idCardNumber = idCardNumber;
	}

	public String getDriverPhotoUrl() {
		return this.driverPhotoUrl;
	}

	public void setDriverPhotoUrl(String driverPhotoUrl) {
		this.driverPhotoUrl = driverPhotoUrl;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public short getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(short recordStatus) {
		this.recordStatus = recordStatus;
	}
}
