package com.claystone.db;
// Generated Mar 17, 2020 5:17:47 PM by Hibernate Tools 3.5.0.Final


import java.util.Date;

/**
 * GpsApiPolling generated by hbm2java
 */
public class GpsApiPolling  implements java.io.Serializable {


     private GpsApiPollingId id;
     private String apiUrl;
     private String apiReqMethod;
     private String apiReqParams;
     private String apiResType;
     private int dataInterval;
     private boolean isUnitActive;
     private int lastResponseCode;
     private int lastDataCount;
     private Date lastProcessedTime;
     private Date lastResponseTime;
     private Date lastModifiedTime;
 	private String licensePlate;
 	private String transporterName;
 	private Date lastGpsdateTime;

 	
    public String getLicensePlate() {
		return licensePlate;
	}

	public void setLicensePlate(String licensePlate) {
		this.licensePlate = licensePlate;
	}

	public String getTransporterName() {
		return transporterName;
	}

	public void setTransporterName(String transporterName) {
		this.transporterName = transporterName;
	}

	public Date getLastGpsdateTime() {
		return lastGpsdateTime;
	}

	public void setLastGpsdateTime(Date lastGpsdateTime) {
		this.lastGpsdateTime = lastGpsdateTime;
	}

	public GpsApiPolling() {
    }

    public GpsApiPolling(GpsApiPollingId id, String apiUrl, String apiReqMethod, String apiReqParams, String apiResType, int dataInterval, boolean isUnitActive, int lastResponseCode, int lastDataCount, Date lastProcessedTime, Date lastResponseTime, Date lastModifiedTime) {
       this.id = id;
       this.apiUrl = apiUrl;
       this.apiReqMethod = apiReqMethod;
       this.apiReqParams = apiReqParams;
       this.apiResType = apiResType;
       this.dataInterval = dataInterval;
       this.isUnitActive = isUnitActive;
       this.lastResponseCode = lastResponseCode;
       this.lastDataCount = lastDataCount;
       this.lastProcessedTime = lastProcessedTime;
       this.lastResponseTime = lastResponseTime;
       this.lastModifiedTime = lastModifiedTime;
    }
   
    public GpsApiPollingId getId() {
        return this.id;
    }
    
    public void setId(GpsApiPollingId id) {
        this.id = id;
    }
    public String getApiUrl() {
        return this.apiUrl;
    }
    
    public void setApiUrl(String apiUrl) {
        this.apiUrl = apiUrl;
    }
    public String getApiReqMethod() {
        return this.apiReqMethod;
    }
    
    public void setApiReqMethod(String apiReqMethod) {
        this.apiReqMethod = apiReqMethod;
    }
    public String getApiReqParams() {
        return this.apiReqParams;
    }
    
    public void setApiReqParams(String apiReqParams) {
        this.apiReqParams = apiReqParams;
    }
    public String getApiResType() {
        return this.apiResType;
    }
    
    public void setApiResType(String apiResType) {
        this.apiResType = apiResType;
    }
    public int getDataInterval() {
        return this.dataInterval;
    }
    
    public void setDataInterval(int dataInterval) {
        this.dataInterval = dataInterval;
    }
    public boolean isIsUnitActive() {
        return this.isUnitActive;
    }
    
    public void setIsUnitActive(boolean isUnitActive) {
        this.isUnitActive = isUnitActive;
    }
    public int getLastResponseCode() {
        return this.lastResponseCode;
    }
    
    public void setLastResponseCode(int lastResponseCode) {
        this.lastResponseCode = lastResponseCode;
    }
    public int getLastDataCount() {
        return this.lastDataCount;
    }
    
    public void setLastDataCount(int lastDataCount) {
        this.lastDataCount = lastDataCount;
    }
    public Date getLastProcessedTime() {
        return this.lastProcessedTime;
    }
    
    public void setLastProcessedTime(Date lastProcessedTime) {
        this.lastProcessedTime = lastProcessedTime;
    }
    public Date getLastResponseTime() {
        return this.lastResponseTime;
    }
    
    public void setLastResponseTime(Date lastResponseTime) {
        this.lastResponseTime = lastResponseTime;
    }
    public Date getLastModifiedTime() {
        return this.lastModifiedTime;
    }
    
    public void setLastModifiedTime(Date lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }




}


