package com.claystone.db;
// Generated Mar 17, 2020 5:17:47 PM by Hibernate Tools 3.5.0.Final

/**
 * GpsApiPollingId generated by hbm2java
 */
public class GpsApiPollingId implements java.io.Serializable {

	private int companyId;
	private String mobileunitid;
	private String searchKey;
	private String dataProviderName;

	public GpsApiPollingId() {
	}

	public GpsApiPollingId(int companyId, String mobileunitid, String searchKey, String dataProviderName) {
		this.companyId = companyId;
		this.mobileunitid = mobileunitid;
		this.searchKey = searchKey;
		this.dataProviderName = dataProviderName;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public String getMobileunitid() {
		return this.mobileunitid;
	}

	public void setMobileunitid(String mobileunitid) {
		this.mobileunitid = mobileunitid;
	}

	public String getSearchKey() {
		return this.searchKey;
	}

	public void setSearchKey(String searchKey) {
		this.searchKey = searchKey;
	}

	public String getDataProviderName() {
		return this.dataProviderName;
	}

	public void setDataProviderName(String dataProviderName) {
		this.dataProviderName = dataProviderName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GpsApiPollingId))
			return false;
		GpsApiPollingId castOther = (GpsApiPollingId) other;

		return (this.getCompanyId() == castOther.getCompanyId())
				&& ((this.getMobileunitid() == castOther.getMobileunitid())
						|| (this.getMobileunitid() != null && castOther.getMobileunitid() != null
								&& this.getMobileunitid().equals(castOther.getMobileunitid())))
				&& ((this.getSearchKey() == castOther.getSearchKey()) || (this.getSearchKey() != null
						&& castOther.getSearchKey() != null && this.getSearchKey().equals(castOther.getSearchKey())))
				&& ((this.getDataProviderName() == castOther.getDataProviderName())
						|| (this.getDataProviderName() != null && castOther.getDataProviderName() != null
								&& this.getDataProviderName().equals(castOther.getDataProviderName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCompanyId();
		result = 37 * result + (getMobileunitid() == null ? 0 : this.getMobileunitid().hashCode());
		result = 37 * result + (getSearchKey() == null ? 0 : this.getSearchKey().hashCode());
		result = 37 * result + (getDataProviderName() == null ? 0 : this.getDataProviderName().hashCode());
		return result;
	}

}
