package com.claystone.db;

// Generated 18 Aug, 2011 1:22:26 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * GpsdataId generated by hbm2java
 */
public class GpsdataId implements java.io.Serializable {

	private String mobileunitid;
	private Date gpsdate;
	private Date gprsdate;

	public GpsdataId() {
	}

	public GpsdataId(String mobileunitid, Date gpsdate, Date gprsdate) {
		this.mobileunitid = mobileunitid;
		this.gpsdate = gpsdate;
		this.gprsdate = gprsdate;
	}

	public String getMobileunitid() {
		return this.mobileunitid;
	}

	public void setMobileunitid(String mobileunitid) {
		this.mobileunitid = mobileunitid;
	}

	public Date getGpsdate() {
		return this.gpsdate;
	}

	public void setGpsdate(Date gpsdate) {
		this.gpsdate = gpsdate;
	}

	public Date getGprsdate() {
		return this.gprsdate;
	}

	public void setGprsdate(Date gprsdate) {
		this.gprsdate = gprsdate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GpsdataId))
			return false;
		GpsdataId castOther = (GpsdataId) other;

		return ((this.getMobileunitid() == castOther.getMobileunitid()) || (this
				.getMobileunitid() != null
				&& castOther.getMobileunitid() != null && this
				.getMobileunitid().equals(castOther.getMobileunitid())))
				&& ((this.getGpsdate() == castOther.getGpsdate()) || (this
						.getGpsdate() != null
						&& castOther.getGpsdate() != null && this.getGpsdate()
						.equals(castOther.getGpsdate())))
				&& ((this.getGprsdate() == castOther.getGprsdate()) || (this
						.getGprsdate() != null
						&& castOther.getGprsdate() != null && this
						.getGprsdate().equals(castOther.getGprsdate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getMobileunitid() == null ? 0 : this.getMobileunitid()
						.hashCode());
		result = 37 * result
				+ (getGpsdate() == null ? 0 : this.getGpsdate().hashCode());
		result = 37 * result
				+ (getGprsdate() == null ? 0 : this.getGprsdate().hashCode());
		return result;
	}

}
