package com.claystone.db;

// Generated 18 Aug, 2011 1:22:26 PM by Hibernate Tools 3.2.4.GA

/**
 * Gpsdata generated by hbm2java
 */
public class Gpsdata implements java.io.Serializable {

	private GpsdataId id;
	private boolean gpsstatus;
	private int latitude;
	private int longitude;
	private short speed;
	private short direction;
	private boolean acc;
	private boolean in1;
	private boolean in2;
	private boolean in3;
	private boolean in4;
	private boolean out1;
	private boolean out2;
	private Short eventcode;
	private Short adc1;
	private Short adc2;
	private Short batt;
	private String reserve;
	private boolean processedFlag;
	private int mileage;

	public Gpsdata() {
	}

	public Gpsdata(GpsdataId id, boolean gpsstatus, int latitude,
			int longitude, short speed, short direction, boolean acc,
			boolean in1, boolean in2, boolean in3, boolean in4, boolean out1,
			boolean out2, boolean processedFlag, int mileage) {
		this.id = id;
		this.gpsstatus = gpsstatus;
		this.latitude = latitude;
		this.longitude = longitude;
		this.speed = speed;
		this.direction = direction;
		this.acc = acc;
		this.in1 = in1;
		this.in2 = in2;
		this.in3 = in3;
		this.in4 = in4;
		this.out1 = out1;
		this.out2 = out2;
		this.processedFlag = processedFlag;
		this.mileage = mileage;
	}

	public Gpsdata(GpsdataId id, boolean gpsstatus, int latitude,
			int longitude, short speed, short direction, boolean acc,
			boolean in1, boolean in2, boolean in3, boolean in4, boolean out1,
			boolean out2, Short eventcode, Short adc1, Short adc2, Short batt,
			String reserve, boolean processedFlag, int mileage) {
		this.id = id;
		this.gpsstatus = gpsstatus;
		this.latitude = latitude;
		this.longitude = longitude;
		this.speed = speed;
		this.direction = direction;
		this.acc = acc;
		this.in1 = in1;
		this.in2 = in2;
		this.in3 = in3;
		this.in4 = in4;
		this.out1 = out1;
		this.out2 = out2;
		this.eventcode = eventcode;
		this.adc1 = adc1;
		this.adc2 = adc2;
		this.batt = batt;
		this.reserve = reserve;
		this.processedFlag = processedFlag;
		this.mileage = mileage;
	}

	public GpsdataId getId() {
		return this.id;
	}

	public void setId(GpsdataId id) {
		this.id = id;
	}

	public boolean isGpsstatus() {
		return this.gpsstatus;
	}

	public void setGpsstatus(boolean gpsstatus) {
		this.gpsstatus = gpsstatus;
	}

	public int getLatitude() {
		return this.latitude;
	}

	public void setLatitude(int latitude) {
		this.latitude = latitude;
	}

	public int getLongitude() {
		return this.longitude;
	}

	public void setLongitude(int longitude) {
		this.longitude = longitude;
	}

	public short getSpeed() {
		return this.speed;
	}

	public void setSpeed(short speed) {
		this.speed = speed;
	}

	public short getDirection() {
		return this.direction;
	}

	public void setDirection(short direction) {
		this.direction = direction;
	}

	public boolean isAcc() {
		return this.acc;
	}

	public void setAcc(boolean acc) {
		this.acc = acc;
	}

	public boolean isIn1() {
		return this.in1;
	}

	public void setIn1(boolean in1) {
		this.in1 = in1;
	}

	public boolean isIn2() {
		return this.in2;
	}

	public void setIn2(boolean in2) {
		this.in2 = in2;
	}

	public boolean isIn3() {
		return this.in3;
	}

	public void setIn3(boolean in3) {
		this.in3 = in3;
	}

	public boolean isIn4() {
		return this.in4;
	}

	public void setIn4(boolean in4) {
		this.in4 = in4;
	}

	public boolean isOut1() {
		return this.out1;
	}

	public void setOut1(boolean out1) {
		this.out1 = out1;
	}

	public boolean isOut2() {
		return this.out2;
	}

	public void setOut2(boolean out2) {
		this.out2 = out2;
	}

	public Short getEventcode() {
		return this.eventcode;
	}

	public void setEventcode(Short eventcode) {
		this.eventcode = eventcode;
	}

	public Short getAdc1() {
		return this.adc1;
	}

	public void setAdc1(Short adc1) {
		this.adc1 = adc1;
	}

	public Short getAdc2() {
		return this.adc2;
	}

	public void setAdc2(Short adc2) {
		this.adc2 = adc2;
	}

	public Short getBatt() {
		return this.batt;
	}

	public void setBatt(Short batt) {
		this.batt = batt;
	}

	public String getReserve() {
		return this.reserve;
	}

	public void setReserve(String reserve) {
		this.reserve = reserve;
	}

	public boolean isProcessedFlag() {
		return this.processedFlag;
	}

	public void setProcessedFlag(boolean processedFlag) {
		this.processedFlag = processedFlag;
	}

	public int getMileage() {
		return this.mileage;
	}

	public void setMileage(int mileage) {
		this.mileage = mileage;
	}

}
