package com.claystone.db;

// Generated 13 Aug, 2012 3:52:09 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * ImeidataId generated by hbm2java
 */
public class ImeidataId implements java.io.Serializable {

	private String imei;
	private String mobileunitid;
	private Date fromdate;

	public ImeidataId() {
	}

	public ImeidataId(String imei, String mobileunitid, Date fromdate) {
		this.imei = imei;
		this.mobileunitid = mobileunitid;
		this.fromdate = fromdate;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public String getMobileunitid() {
		return this.mobileunitid;
	}

	public void setMobileunitid(String mobileunitid) {
		this.mobileunitid = mobileunitid;
	}

	public Date getFromdate() {
		return this.fromdate;
	}

	public void setFromdate(Date fromdate) {
		this.fromdate = fromdate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImeidataId))
			return false;
		ImeidataId castOther = (ImeidataId) other;

		return ((this.getImei() == castOther.getImei()) || (this.getImei() != null
				&& castOther.getImei() != null && this.getImei().equals(
				castOther.getImei())))
				&& ((this.getMobileunitid() == castOther.getMobileunitid()) || (this
						.getMobileunitid() != null
						&& castOther.getMobileunitid() != null && this
						.getMobileunitid().equals(castOther.getMobileunitid())))
				&& ((this.getFromdate() == castOther.getFromdate()) || (this
						.getFromdate() != null
						&& castOther.getFromdate() != null && this
						.getFromdate().equals(castOther.getFromdate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getImei() == null ? 0 : this.getImei().hashCode());
		result = 37
				* result
				+ (getMobileunitid() == null ? 0 : this.getMobileunitid()
						.hashCode());
		result = 37 * result
				+ (getFromdate() == null ? 0 : this.getFromdate().hashCode());
		return result;
	}

}
