package com.claystone.db;

// Generated 13 Aug, 2012 3:52:09 PM by Hibernate Tools 3.2.4.GA

/**
 * Imeidata generated by hbm2java
 */
public class Imeidata implements java.io.Serializable {

	private ImeidataId id;
	private Boolean doorFlag;
	private Integer sensor;

	public Imeidata() {
	}

	public Imeidata(ImeidataId id) {
		this.id = id;
	}

	public Imeidata(ImeidataId id, Boolean doorFlag) {
		this.id = id;
		this.doorFlag = doorFlag;
	}

	public ImeidataId getId() {
		return this.id;
	}

	public void setId(ImeidataId id) {
		this.id = id;
	}

	public Boolean getDoorFlag() {
		return this.doorFlag;
	}

	public void setDoorFlag(Boolean doorFlag) {
		this.doorFlag = doorFlag;
	}

	public Integer getSensor() {
		return sensor;
	}

	public void setSensor(Integer sensor) {
		this.sensor = sensor;
	}

}
