package com.claystone.db; import java.util.Date;

import net.sf.gilead.pojo.java5.LightEntity;

/**
 * MobileUnit generated by hbm2java
 */
public class MobileUnit extends LightEntity implements java.io.Serializable {

	// Fields    

	/**
	 * 
	 */
	private static final long serialVersionUID = 853218524112720305L;

	private MobileUnitId id;

	private String mobileUnitDescEn;

	private String mobileUnitDescNative;

	private String hardwareId;

	private Date lastModifiedTime;

	private String lastModifiedUser;

	private short recordStatus;

	// Constructors

	/** default constructor */
	public MobileUnit() {
	}

	/** minimal constructor */
	public MobileUnit(MobileUnitId id, Date lastModifiedTime,
			String lastModifiedUser, short recordStatus) {
		this.id = id;
		this.lastModifiedTime = lastModifiedTime;
		this.lastModifiedUser = lastModifiedUser;
		this.recordStatus = recordStatus;
	}

	/** full constructor */
	public MobileUnit(MobileUnitId id, String mobileUnitDescEn,
			String mobileUnitDescNative, String hardwareId,
			Date lastModifiedTime, String lastModifiedUser, short recordStatus) {
		this.id = id;
		this.mobileUnitDescEn = mobileUnitDescEn;
		this.mobileUnitDescNative = mobileUnitDescNative;
		this.hardwareId = hardwareId;
		this.lastModifiedTime = lastModifiedTime;
		this.lastModifiedUser = lastModifiedUser;
		this.recordStatus = recordStatus;
	}

	// Property accessors
	public MobileUnitId getId() {
		return this.id;
	}

	public void setId(MobileUnitId id) {
		this.id = id;
	}

	public String getMobileUnitDescEn() {
		return this.mobileUnitDescEn;
	}

	public void setMobileUnitDescEn(String mobileUnitDescEn) {
		this.mobileUnitDescEn = mobileUnitDescEn;
	}

	public String getMobileUnitDescNative() {
		return this.mobileUnitDescNative;
	}

	public void setMobileUnitDescNative(String mobileUnitDescNative) {
		this.mobileUnitDescNative = mobileUnitDescNative;
	}

	public String getHardwareId() {
		return this.hardwareId;
	}

	public void setHardwareId(String hardwareId) {
		this.hardwareId = hardwareId;
	}

	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	public String getLastModifiedUser() {
		return this.lastModifiedUser;
	}

	public void setLastModifiedUser(String lastModifiedUser) {
		this.lastModifiedUser = lastModifiedUser;
	}

	public short getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(short recordStatus) {
		this.recordStatus = recordStatus;
	}

}
