package com.claystone.db; import net.sf.gilead.pojo.java5.LightEntity;

// Generated Dec 24, 2007 1:46:17 PM by Hibernate Tools 3.1.0.beta5

/**
 * MobileUnitId generated by hbm2java
 */
public class MobileUnitId extends LightEntity implements java.io.Serializable {

	// Fields    

	/**
	 * 
	 */
	private static final long serialVersionUID = 110054269877259933L;

	private String mobileunitid;

	private int companyId;

	// Constructors

	/** default constructor */
	public MobileUnitId() {
	}

	/** full constructor */
	public MobileUnitId(String mobileunitid, int companyId) {
		this.mobileunitid = mobileunitid;
		this.companyId = companyId;
	}

	// Property accessors
	public String getMobileunitid() {
		return this.mobileunitid;
	}

	public void setMobileunitid(String mobileunitid) {
		this.mobileunitid = mobileunitid;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MobileUnitId))
			return false;
		MobileUnitId castOther = (MobileUnitId) other;

		return ((this.getMobileunitid() == castOther.getMobileunitid()) || (this
				.getMobileunitid() != null
				&& castOther.getMobileunitid() != null && this
				.getMobileunitid().equals(castOther.getMobileunitid())))
				&& (this.getCompanyId() == castOther.getCompanyId());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getMobileunitid() == null ? 0 : this.getMobileunitid()
						.hashCode());
		result = 37 * result + this.getCompanyId();
		return result;
	}

}
