package com.claystone.db;
// Generated 11 Oct, 2017 2:05:59 PM by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * OrRoute generated by hbm2java
 */
public class OrRoute implements java.io.Serializable {

	private OrRouteId id;
	private String routeName;
	private String stationName;
	private String stationType;
	private short recordStatus;
	private Date lastEffectiveDate;
	private Date lastModifiedTime;
	private String lastModifiedUser;
	private String bayNumber;
	private int distance;
	private int workgroupId;
	private String shipmentId;
	private Date arrivalDate;
	private Integer routeStatus;
	private String routeType;
	private String alertEmailId;
	private String alertMobileNo;

	public OrRoute() {
	}

	public OrRoute(OrRouteId id, String routeName, String stationName, String stationType, short recordStatus,
			Date lastEffectiveDate, Date lastModifiedTime, String lastModifiedUser, int distance, int workgroupId) {
		this.id = id;
		this.routeName = routeName;
		this.stationName = stationName;
		this.stationType = stationType;
		this.recordStatus = recordStatus;
		this.lastEffectiveDate = lastEffectiveDate;
		this.lastModifiedTime = lastModifiedTime;
		this.lastModifiedUser = lastModifiedUser;
		this.distance = distance;
		this.workgroupId = workgroupId;
	}

	public OrRoute(OrRouteId id, String routeName, String stationName, String stationType, short recordStatus,
			Date lastEffectiveDate, Date lastModifiedTime, String lastModifiedUser, String bayNumber, int distance,
			int workgroupId, String shipmentId, Date arrivalDate, Integer routeStatus, String routeType, String alertEmailId, String alertMobileNo) {
		this.id = id;
		this.routeName = routeName;
		this.stationName = stationName;
		this.stationType = stationType;
		this.recordStatus = recordStatus;
		this.lastEffectiveDate = lastEffectiveDate;
		this.lastModifiedTime = lastModifiedTime;
		this.lastModifiedUser = lastModifiedUser;
		this.bayNumber = bayNumber;
		this.distance = distance;
		this.workgroupId = workgroupId;
		this.shipmentId = shipmentId;
		this.arrivalDate = arrivalDate;
		this.routeStatus = routeStatus;
		this.routeType = routeType;
		this.alertEmailId = alertEmailId;
		this.alertMobileNo = alertMobileNo;
	}

	public OrRouteId getId() {
		return this.id;
	}

	public void setId(OrRouteId id) {
		this.id = id;
	}

	public String getRouteName() {
		return this.routeName;
	}

	public void setRouteName(String routeName) {
		this.routeName = routeName;
	}

	public String getStationName() {
		return this.stationName;
	}

	public void setStationName(String stationName) {
		this.stationName = stationName;
	}

	public String getStationType() {
		return this.stationType;
	}

	public void setStationType(String stationType) {
		this.stationType = stationType;
	}

	public short getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(short recordStatus) {
		this.recordStatus = recordStatus;
	}

	public Date getLastEffectiveDate() {
		return this.lastEffectiveDate;
	}

	public void setLastEffectiveDate(Date lastEffectiveDate) {
		this.lastEffectiveDate = lastEffectiveDate;
	}

	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	public String getLastModifiedUser() {
		return this.lastModifiedUser;
	}

	public void setLastModifiedUser(String lastModifiedUser) {
		this.lastModifiedUser = lastModifiedUser;
	}

	public String getBayNumber() {
		return this.bayNumber;
	}

	public void setBayNumber(String bayNumber) {
		this.bayNumber = bayNumber;
	}

	public int getDistance() {
		return this.distance;
	}

	public void setDistance(int distance) {
		this.distance = distance;
	}

	public int getWorkgroupId() {
		return this.workgroupId;
	}

	public void setWorkgroupId(int workgroupId) {
		this.workgroupId = workgroupId;
	}

	public String getShipmentId() {
		return this.shipmentId;
	}

	public void setShipmentId(String shipmentId) {
		this.shipmentId = shipmentId;
	}

	public Date getArrivalDate() {
		return this.arrivalDate;
	}

	public void setArrivalDate(Date arrivalDate) {
		this.arrivalDate = arrivalDate;
	}

	public Integer getRouteStatus() {
		return this.routeStatus;
	}

	public void setRouteStatus(Integer routeStatus) {
		this.routeStatus = routeStatus;
	}

	public String getRouteType() {
		return this.routeType;
	}

	public void setRouteType(String routeType) {
		this.routeType = routeType;
	}

	public String getAlertEmailId() {
		return alertEmailId;
	}

	public void setAlertEmailId(String alertEmailId) {
		this.alertEmailId = alertEmailId;
	}

	public String getAlertMobileNo() {
		return alertMobileNo;
	}

	public void setAlertMobileNo(String alertMobileNo) {
		this.alertMobileNo = alertMobileNo;
	}

}
