package com.claystone.db;
// Generated 16 Oct, 2017 10:45:38 AM by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * OrRouteVehicleId generated by hbm2java
 */
public class OrRouteVehicleId implements java.io.Serializable {

	private int vehicleId;
	private int companyId;
	private int routeId;
	private Date firstEffectiveDate;

	public OrRouteVehicleId() {
	}

	public OrRouteVehicleId(int vehicleId, int companyId, int routeId, Date firstEffectiveDate) {
		this.vehicleId = vehicleId;
		this.companyId = companyId;
		this.routeId = routeId;
		this.firstEffectiveDate = firstEffectiveDate;
	}

	public int getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(int vehicleId) {
		this.vehicleId = vehicleId;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public int getRouteId() {
		return this.routeId;
	}

	public void setRouteId(int routeId) {
		this.routeId = routeId;
	}

	public Date getFirstEffectiveDate() {
		return this.firstEffectiveDate;
	}

	public void setFirstEffectiveDate(Date firstEffectiveDate) {
		this.firstEffectiveDate = firstEffectiveDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrRouteVehicleId))
			return false;
		OrRouteVehicleId castOther = (OrRouteVehicleId) other;

		return (this.getVehicleId() == castOther.getVehicleId()) && (this.getCompanyId() == castOther.getCompanyId())
				&& (this.getRouteId() == castOther.getRouteId())
				&& ((this.getFirstEffectiveDate() == castOther.getFirstEffectiveDate())
						|| (this.getFirstEffectiveDate() != null && castOther.getFirstEffectiveDate() != null
								&& this.getFirstEffectiveDate().equals(castOther.getFirstEffectiveDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getVehicleId();
		result = 37 * result + this.getCompanyId();
		result = 37 * result + this.getRouteId();
		result = 37 * result + (getFirstEffectiveDate() == null ? 0 : this.getFirstEffectiveDate().hashCode());
		return result;
	}

}
