package com.claystone.db;
// Generated 16 Oct, 2017 10:45:38 AM by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * OrRouteVehicle generated by hbm2java
 */
public class OrRouteVehicle implements java.io.Serializable {

	private OrRouteVehicleId id;
	private String licensePlate;
	private Date lastEffectiveDate;
	private Date lastModifiedTime;
	private String lastModifiedUser;
	private String tripDocumentNo;
	private Integer timingTripId;
	private Integer priority;
	private Integer currentStatus;

	public OrRouteVehicle() {
	}

	public OrRouteVehicle(OrRouteVehicleId id, String licensePlate, Date lastEffectiveDate, Date lastModifiedTime,
			String lastModifiedUser) {
		this.id = id;
		this.licensePlate = licensePlate;
		this.lastEffectiveDate = lastEffectiveDate;
		this.lastModifiedTime = lastModifiedTime;
		this.lastModifiedUser = lastModifiedUser;
	}

	public OrRouteVehicle(OrRouteVehicleId id, String licensePlate, Date lastEffectiveDate, Date lastModifiedTime,
			String lastModifiedUser, String tripDocumentNo, Integer timingTripId, Integer priority,
			Integer currentStatus) {
		this.id = id;
		this.licensePlate = licensePlate;
		this.lastEffectiveDate = lastEffectiveDate;
		this.lastModifiedTime = lastModifiedTime;
		this.lastModifiedUser = lastModifiedUser;
		this.tripDocumentNo = tripDocumentNo;
		this.timingTripId = timingTripId;
		this.priority = priority;
		this.currentStatus = currentStatus;
	}

	public OrRouteVehicleId getId() {
		return this.id;
	}

	public void setId(OrRouteVehicleId id) {
		this.id = id;
	}

	public String getLicensePlate() {
		return this.licensePlate;
	}

	public void setLicensePlate(String licensePlate) {
		this.licensePlate = licensePlate;
	}

	public Date getLastEffectiveDate() {
		return this.lastEffectiveDate;
	}

	public void setLastEffectiveDate(Date lastEffectiveDate) {
		this.lastEffectiveDate = lastEffectiveDate;
	}

	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	public String getLastModifiedUser() {
		return this.lastModifiedUser;
	}

	public void setLastModifiedUser(String lastModifiedUser) {
		this.lastModifiedUser = lastModifiedUser;
	}

	public String getTripDocumentNo() {
		return this.tripDocumentNo;
	}

	public void setTripDocumentNo(String tripDocumentNo) {
		this.tripDocumentNo = tripDocumentNo;
	}

	public Integer getTimingTripId() {
		return this.timingTripId;
	}

	public void setTimingTripId(Integer timingTripId) {
		this.timingTripId = timingTripId;
	}

	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	public Integer getCurrentStatus() {
		return this.currentStatus;
	}

	public void setCurrentStatus(Integer currentStatus) {
		this.currentStatus = currentStatus;
	}

}
