package com.claystone.db;
// Generated 11 Oct, 2017 2:05:59 PM by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * OrRouteId generated by hbm2java
 */
public class OrRouteId implements java.io.Serializable {

	private int routeId;
	private int companyId;
	private short stationSequence;
	private int stationId;
	private Date firstEffectiveDate;

	public OrRouteId() {
	}

	public OrRouteId(int routeId, int companyId, short stationSequence, int stationId, Date firstEffectiveDate) {
		this.routeId = routeId;
		this.companyId = companyId;
		this.stationSequence = stationSequence;
		this.stationId = stationId;
		this.firstEffectiveDate = firstEffectiveDate;
	}

	public int getRouteId() {
		return this.routeId;
	}

	public void setRouteId(int routeId) {
		this.routeId = routeId;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public short getStationSequence() {
		return this.stationSequence;
	}

	public void setStationSequence(short stationSequence) {
		this.stationSequence = stationSequence;
	}

	public int getStationId() {
		return this.stationId;
	}

	public void setStationId(int stationId) {
		this.stationId = stationId;
	}

	public Date getFirstEffectiveDate() {
		return this.firstEffectiveDate;
	}

	public void setFirstEffectiveDate(Date firstEffectiveDate) {
		this.firstEffectiveDate = firstEffectiveDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrRouteId))
			return false;
		OrRouteId castOther = (OrRouteId) other;

		return (this.getRouteId() == castOther.getRouteId()) && (this.getCompanyId() == castOther.getCompanyId())
				&& (this.getStationSequence() == castOther.getStationSequence())
				&& (this.getStationId() == castOther.getStationId())
				&& ((this.getFirstEffectiveDate() == castOther.getFirstEffectiveDate())
						|| (this.getFirstEffectiveDate() != null && castOther.getFirstEffectiveDate() != null
								&& this.getFirstEffectiveDate().equals(castOther.getFirstEffectiveDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRouteId();
		result = 37 * result + this.getCompanyId();
		result = 37 * result + this.getStationSequence();
		result = 37 * result + this.getStationId();
		result = 37 * result + (getFirstEffectiveDate() == null ? 0 : this.getFirstEffectiveDate().hashCode());
		return result;
	}

}
