package com.claystone.db;

// Generated 13 Jan, 2015 11:38:56 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * OrRouteTimings generated by hbm2java
 */
public class OrRouteTimings implements java.io.Serializable {

	private OrRouteTimingsId id;
	private String routeName;
	private String stationName;
	private String stationType;
	private String definedArrivalTime;
	private String definedDeptTime;
	private short definedStoppageTime;
	private short recordStatus;
	private Date firstEffectiveDate;
	private Date lastEffectiveDate;
	private Date lastModifiedTime;
	private String lastModifiedUser;
	private Integer arrivalDay;
	private Integer departureDay;
	private Date arrivalDate;
	private Date deptDate;

	public OrRouteTimings() {
	}

	public OrRouteTimings(OrRouteTimingsId id, String routeName,
			String stationName, String stationType, String definedArrivalTime,
			String definedDeptTime, short definedStoppageTime,
			short recordStatus, Date firstEffectiveDate,
			Date lastEffectiveDate, Date lastModifiedTime,
			String lastModifiedUser) {
		this.id = id;
		this.routeName = routeName;
		this.stationName = stationName;
		this.stationType = stationType;
		this.definedArrivalTime = definedArrivalTime;
		this.definedDeptTime = definedDeptTime;
		this.definedStoppageTime = definedStoppageTime;
		this.recordStatus = recordStatus;
		this.firstEffectiveDate = firstEffectiveDate;
		this.lastEffectiveDate = lastEffectiveDate;
		this.lastModifiedTime = lastModifiedTime;
		this.lastModifiedUser = lastModifiedUser;
	}

	public OrRouteTimings(OrRouteTimingsId id, String routeName,
			String stationName, String stationType, String definedArrivalTime,
			String definedDeptTime, short definedStoppageTime,
			short recordStatus, Date firstEffectiveDate,
			Date lastEffectiveDate, Date lastModifiedTime,
			String lastModifiedUser, Integer arrivalDay, Integer departureDay,
			Date arrivalDate, Date deptDate) {
		this.id = id;
		this.routeName = routeName;
		this.stationName = stationName;
		this.stationType = stationType;
		this.definedArrivalTime = definedArrivalTime;
		this.definedDeptTime = definedDeptTime;
		this.definedStoppageTime = definedStoppageTime;
		this.recordStatus = recordStatus;
		this.firstEffectiveDate = firstEffectiveDate;
		this.lastEffectiveDate = lastEffectiveDate;
		this.lastModifiedTime = lastModifiedTime;
		this.lastModifiedUser = lastModifiedUser;
		this.arrivalDay = arrivalDay;
		this.departureDay = departureDay;
		this.arrivalDate = arrivalDate;
		this.deptDate = deptDate;
	}

	public OrRouteTimingsId getId() {
		return this.id;
	}

	public void setId(OrRouteTimingsId id) {
		this.id = id;
	}

	public String getRouteName() {
		return this.routeName;
	}

	public void setRouteName(String routeName) {
		this.routeName = routeName;
	}

	public String getStationName() {
		return this.stationName;
	}

	public void setStationName(String stationName) {
		this.stationName = stationName;
	}

	public String getStationType() {
		return this.stationType;
	}

	public void setStationType(String stationType) {
		this.stationType = stationType;
	}

	public String getDefinedArrivalTime() {
		return this.definedArrivalTime;
	}

	public void setDefinedArrivalTime(String definedArrivalTime) {
		this.definedArrivalTime = definedArrivalTime;
	}

	public String getDefinedDeptTime() {
		return this.definedDeptTime;
	}

	public void setDefinedDeptTime(String definedDeptTime) {
		this.definedDeptTime = definedDeptTime;
	}

	public short getDefinedStoppageTime() {
		return this.definedStoppageTime;
	}

	public void setDefinedStoppageTime(short definedStoppageTime) {
		this.definedStoppageTime = definedStoppageTime;
	}

	public short getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(short recordStatus) {
		this.recordStatus = recordStatus;
	}

	public Date getFirstEffectiveDate() {
		return this.firstEffectiveDate;
	}

	public void setFirstEffectiveDate(Date firstEffectiveDate) {
		this.firstEffectiveDate = firstEffectiveDate;
	}

	public Date getLastEffectiveDate() {
		return this.lastEffectiveDate;
	}

	public void setLastEffectiveDate(Date lastEffectiveDate) {
		this.lastEffectiveDate = lastEffectiveDate;
	}

	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	public String getLastModifiedUser() {
		return this.lastModifiedUser;
	}

	public void setLastModifiedUser(String lastModifiedUser) {
		this.lastModifiedUser = lastModifiedUser;
	}

	public Integer getArrivalDay() {
		return this.arrivalDay;
	}

	public void setArrivalDay(Integer arrivalDay) {
		this.arrivalDay = arrivalDay;
	}

	public Integer getDepartureDay() {
		return this.departureDay;
	}

	public void setDepartureDay(Integer departureDay) {
		this.departureDay = departureDay;
	}

	public Date getArrivalDate() {
		return arrivalDate;
	}

	public void setArrivalDate(Date arrivalDate) {
		this.arrivalDate = arrivalDate;
	}

	public Date getDeptDate() {
		return deptDate;
	}

	public void setDeptDate(Date deptDate) {
		this.deptDate = deptDate;
	}

}
