package com.claystone.db;

// Generated 13 Jan, 2015 11:38:56 AM by Hibernate Tools 4.0.0

/**
 * OrRouteTimingsId generated by hbm2java
 */
public class OrRouteTimingsId implements java.io.Serializable {

	private int tripId;
	private int companyId;
	private short stationSequence;
	private int routeId;
	private int stationId;

	public OrRouteTimingsId() {
	}

	public OrRouteTimingsId(int tripId, int companyId, short stationSequence,
			int routeId, int stationId) {
		this.tripId = tripId;
		this.companyId = companyId;
		this.stationSequence = stationSequence;
		this.routeId = routeId;
		this.stationId = stationId;
	}

	public int getTripId() {
		return this.tripId;
	}

	public void setTripId(int tripId) {
		this.tripId = tripId;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public short getStationSequence() {
		return this.stationSequence;
	}

	public void setStationSequence(short stationSequence) {
		this.stationSequence = stationSequence;
	}

	public int getRouteId() {
		return this.routeId;
	}

	public void setRouteId(int routeId) {
		this.routeId = routeId;
	}

	public int getStationId() {
		return this.stationId;
	}

	public void setStationId(int stationId) {
		this.stationId = stationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrRouteTimingsId))
			return false;
		OrRouteTimingsId castOther = (OrRouteTimingsId) other;

		return (this.getTripId() == castOther.getTripId())
				&& (this.getCompanyId() == castOther.getCompanyId())
				&& (this.getStationSequence() == castOther.getStationSequence())
				&& (this.getRouteId() == castOther.getRouteId())
				&& (this.getStationId() == castOther.getStationId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTripId();
		result = 37 * result + this.getCompanyId();
		result = 37 * result + this.getStationSequence();
		result = 37 * result + this.getRouteId();
		result = 37 * result + this.getStationId();
		return result;
	}

}
