package com.claystone.db;
// Generated May 14, 2019 10:32:33 AM by Hibernate Tools 5.3.6.Final


import java.util.Date;

/**
 * OrTripInfo generated by hbm2java
 */
public class OrTripInfo  implements java.io.Serializable {


     private OrTripInfoId id;
     private String createdBy;
     private Date createdTime;
     private int vehicleId;
     private short tripStatus;
     private boolean tripAutoTrack;
     private Date tripStartTime;
     private Date tripEndTime;
     private int tripDistancePlanned;
     private int tripDistanceActual;
     private short recordStatus;
     private Date lastModifiedTime;
     private String lastModifiedUser;
     private short tripOnwardReturnFlag;
     private String routeCode;
     private String bayNumber;
     private String tripDocumentNo;
     private Boolean processedFlag;
     private String tripTypeFlag;
     private Date actualTripStartTime;
     private Date manualStartTime;
     private Date manualEndTime;
     private Integer manualTripStatus;
     private Integer manualStartLatitude;
     private Integer manualStartLongitude;
     private Integer manualEndLatitude;
     private Integer manualEndLongitude;
     private String remarks;

    public OrTripInfo() {
    }

	
    public OrTripInfo(OrTripInfoId id, String createdBy, Date createdTime, int vehicleId, short tripStatus, boolean tripAutoTrack, Date tripStartTime, Date tripEndTime, int tripDistancePlanned, int tripDistanceActual, short recordStatus, Date lastModifiedTime, String lastModifiedUser, short tripOnwardReturnFlag) {
        this.id = id;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.vehicleId = vehicleId;
        this.tripStatus = tripStatus;
        this.tripAutoTrack = tripAutoTrack;
        this.tripStartTime = tripStartTime;
        this.tripEndTime = tripEndTime;
        this.tripDistancePlanned = tripDistancePlanned;
        this.tripDistanceActual = tripDistanceActual;
        this.recordStatus = recordStatus;
        this.lastModifiedTime = lastModifiedTime;
        this.lastModifiedUser = lastModifiedUser;
        this.tripOnwardReturnFlag = tripOnwardReturnFlag;
    }
    public OrTripInfo(OrTripInfoId id, String createdBy, Date createdTime, int vehicleId, short tripStatus, boolean tripAutoTrack, Date tripStartTime, Date tripEndTime, int tripDistancePlanned, int tripDistanceActual, short recordStatus, Date lastModifiedTime, String lastModifiedUser, short tripOnwardReturnFlag, String routeCode, String bayNumber, String tripDocumentNo, Boolean processedFlag, String tripTypeFlag, Date actualTripStartTime, Date manualStartTime, Date manualEndTime, Integer manualTripStatus, Integer manualStartLatitude, Integer manualStartLongitude, Integer manualEndLatitude, Integer manualEndLongitude, String remarks) {
       this.id = id;
       this.createdBy = createdBy;
       this.createdTime = createdTime;
       this.vehicleId = vehicleId;
       this.tripStatus = tripStatus;
       this.tripAutoTrack = tripAutoTrack;
       this.tripStartTime = tripStartTime;
       this.tripEndTime = tripEndTime;
       this.tripDistancePlanned = tripDistancePlanned;
       this.tripDistanceActual = tripDistanceActual;
       this.recordStatus = recordStatus;
       this.lastModifiedTime = lastModifiedTime;
       this.lastModifiedUser = lastModifiedUser;
       this.tripOnwardReturnFlag = tripOnwardReturnFlag;
       this.routeCode = routeCode;
       this.bayNumber = bayNumber;
       this.tripDocumentNo = tripDocumentNo;
       this.processedFlag = processedFlag;
       this.tripTypeFlag = tripTypeFlag;
       this.actualTripStartTime = actualTripStartTime;
       this.manualStartTime = manualStartTime;
       this.manualEndTime = manualEndTime;
       this.manualTripStatus = manualTripStatus;
       this.manualStartLatitude = manualStartLatitude;
       this.manualStartLongitude = manualStartLongitude;
       this.manualEndLatitude = manualEndLatitude;
       this.manualEndLongitude = manualEndLongitude;
       this.remarks = remarks;
    }
   
    public OrTripInfoId getId() {
        return this.id;
    }
    
    public void setId(OrTripInfoId id) {
        this.id = id;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    public int getVehicleId() {
        return this.vehicleId;
    }
    
    public void setVehicleId(int vehicleId) {
        this.vehicleId = vehicleId;
    }
    public short getTripStatus() {
        return this.tripStatus;
    }
    
    public void setTripStatus(short tripStatus) {
        this.tripStatus = tripStatus;
    }
    public boolean isTripAutoTrack() {
        return this.tripAutoTrack;
    }
    
    public void setTripAutoTrack(boolean tripAutoTrack) {
        this.tripAutoTrack = tripAutoTrack;
    }
    public Date getTripStartTime() {
        return this.tripStartTime;
    }
    
    public void setTripStartTime(Date tripStartTime) {
        this.tripStartTime = tripStartTime;
    }
    public Date getTripEndTime() {
        return this.tripEndTime;
    }
    
    public void setTripEndTime(Date tripEndTime) {
        this.tripEndTime = tripEndTime;
    }
    public int getTripDistancePlanned() {
        return this.tripDistancePlanned;
    }
    
    public void setTripDistancePlanned(int tripDistancePlanned) {
        this.tripDistancePlanned = tripDistancePlanned;
    }
    public int getTripDistanceActual() {
        return this.tripDistanceActual;
    }
    
    public void setTripDistanceActual(int tripDistanceActual) {
        this.tripDistanceActual = tripDistanceActual;
    }
    public short getRecordStatus() {
        return this.recordStatus;
    }
    
    public void setRecordStatus(short recordStatus) {
        this.recordStatus = recordStatus;
    }
    public Date getLastModifiedTime() {
        return this.lastModifiedTime;
    }
    
    public void setLastModifiedTime(Date lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }
    public String getLastModifiedUser() {
        return this.lastModifiedUser;
    }
    
    public void setLastModifiedUser(String lastModifiedUser) {
        this.lastModifiedUser = lastModifiedUser;
    }
    public short getTripOnwardReturnFlag() {
        return this.tripOnwardReturnFlag;
    }
    
    public void setTripOnwardReturnFlag(short tripOnwardReturnFlag) {
        this.tripOnwardReturnFlag = tripOnwardReturnFlag;
    }
    public String getRouteCode() {
        return this.routeCode;
    }
    
    public void setRouteCode(String routeCode) {
        this.routeCode = routeCode;
    }
    public String getBayNumber() {
        return this.bayNumber;
    }
    
    public void setBayNumber(String bayNumber) {
        this.bayNumber = bayNumber;
    }
    public String getTripDocumentNo() {
        return this.tripDocumentNo;
    }
    
    public void setTripDocumentNo(String tripDocumentNo) {
        this.tripDocumentNo = tripDocumentNo;
    }
    public Boolean getProcessedFlag() {
        return this.processedFlag;
    }
    
    public void setProcessedFlag(Boolean processedFlag) {
        this.processedFlag = processedFlag;
    }
    public String getTripTypeFlag() {
        return this.tripTypeFlag;
    }
    
    public void setTripTypeFlag(String tripTypeFlag) {
        this.tripTypeFlag = tripTypeFlag;
    }
    public Date getActualTripStartTime() {
        return this.actualTripStartTime;
    }
    
    public void setActualTripStartTime(Date actualTripStartTime) {
        this.actualTripStartTime = actualTripStartTime;
    }
    public Date getManualStartTime() {
        return this.manualStartTime;
    }
    
    public void setManualStartTime(Date manualStartTime) {
        this.manualStartTime = manualStartTime;
    }
    public Date getManualEndTime() {
        return this.manualEndTime;
    }
    
    public void setManualEndTime(Date manualEndTime) {
        this.manualEndTime = manualEndTime;
    }
    public Integer getManualTripStatus() {
        return this.manualTripStatus;
    }
    
    public void setManualTripStatus(Integer manualTripStatus) {
        this.manualTripStatus = manualTripStatus;
    }
    public Integer getManualStartLatitude() {
        return this.manualStartLatitude;
    }
    
    public void setManualStartLatitude(Integer manualStartLatitude) {
        this.manualStartLatitude = manualStartLatitude;
    }
    public Integer getManualStartLongitude() {
        return this.manualStartLongitude;
    }
    
    public void setManualStartLongitude(Integer manualStartLongitude) {
        this.manualStartLongitude = manualStartLongitude;
    }
    public Integer getManualEndLatitude() {
        return this.manualEndLatitude;
    }
    
    public void setManualEndLatitude(Integer manualEndLatitude) {
        this.manualEndLatitude = manualEndLatitude;
    }
    public Integer getManualEndLongitude() {
        return this.manualEndLongitude;
    }
    
    public void setManualEndLongitude(Integer manualEndLongitude) {
        this.manualEndLongitude = manualEndLongitude;
    }
	public String getRemarks() {
		return remarks;
	}
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
}