package com.claystone.db;
// Generated May 14, 2019 10:32:33 AM by Hibernate Tools 5.3.6.Final



/**
 * OrTripStationsNewId generated by hbm2java
 */
public class OrTripStationsNewId  implements java.io.Serializable {


     private int tripId;
     private int companyId;
     private short stationSequence;
     private int stationId;

    public OrTripStationsNewId() {
    }

    public OrTripStationsNewId(int tripId, int companyId, short stationSequence, int stationId) {
       this.tripId = tripId;
       this.companyId = companyId;
       this.stationSequence = stationSequence;
       this.stationId = stationId;
    }
   
    public int getTripId() {
        return this.tripId;
    }
    
    public void setTripId(int tripId) {
        this.tripId = tripId;
    }
    public int getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }
    public short getStationSequence() {
        return this.stationSequence;
    }
    
    public void setStationSequence(short stationSequence) {
        this.stationSequence = stationSequence;
    }
    public int getStationId() {
        return this.stationId;
    }
    
    public void setStationId(int stationId) {
        this.stationId = stationId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrTripStationsNewId) ) return false;
		 OrTripStationsNewId castOther = ( OrTripStationsNewId ) other; 
         
		 return (this.getTripId()==castOther.getTripId())
 && (this.getCompanyId()==castOther.getCompanyId())
 && (this.getStationSequence()==castOther.getStationSequence())
 && (this.getStationId()==castOther.getStationId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTripId();
         result = 37 * result + this.getCompanyId();
         result = 37 * result + this.getStationSequence();
         result = 37 * result + this.getStationId();
         return result;
   }   


}


