package com.claystone.db;
// Generated May 14, 2019 10:32:33 AM by Hibernate Tools 5.3.6.Final



/**
 * OrTripInfoId generated by hbm2java
 */
public class OrTripInfoId  implements java.io.Serializable {


     private int tripId;
     private int companyId;

    public OrTripInfoId() {
    }

    public OrTripInfoId(int tripId, int companyId) {
       this.tripId = tripId;
       this.companyId = companyId;
    }
   
    public int getTripId() {
        return this.tripId;
    }
    
    public void setTripId(int tripId) {
        this.tripId = tripId;
    }
    public int getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrTripInfoId) ) return false;
		 OrTripInfoId castOther = ( OrTripInfoId ) other; 
         
		 return (this.getTripId()==castOther.getTripId())
 && (this.getCompanyId()==castOther.getCompanyId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTripId();
         result = 37 * result + this.getCompanyId();
         return result;
   }   


}


