package com.claystone.db;
// Generated May 14, 2019 10:32:33 AM by Hibernate Tools 5.3.6.Final


import java.util.Date;

/**
 * OrTripStationsNew generated by hbm2java
 */
public class OrTripStationsNew  implements java.io.Serializable {


     private OrTripStationsNewId id;
     private String stationType;
     private int tripReceiverId;
     private Date definedArrivalTime;
     private Date definedDeptTime;
     private short definedStoppageTime;
     private Date actualArrivalTime;
     private Date actualDeptTime;
     private short actualStoppageTime;
     private short vehiclePosition;
     private short recordStatus;
     private Date lastModifiedTime;
     private String lastModifiedUser;
     private Date manualIn;
     private Date manualOut;
     private Short manualStoppageTime;
     private Short manualVehiclePosition;
     private Integer manualInLatitude;
     private Integer manualInLongitude;
     private Integer manualOutLatitude;
     private Integer manualOutLongitude;
     private Boolean manualEntryWarningSent;
     private Boolean manualEntryOverrideFlag;
     private Integer radius;
     private Boolean insideRadius;
     private Boolean podflag;
     private String contactName;
     private String emailId;
     private String countryCode;
     private String contactNumber;
     private Boolean manualExitWarningSent;
     private Boolean manualExitOverrideFlag;
     private String skipReason;

    public OrTripStationsNew() {
    }

	
    public OrTripStationsNew(OrTripStationsNewId id, String stationType, int tripReceiverId, Date definedArrivalTime, Date definedDeptTime, short definedStoppageTime, Date actualArrivalTime, Date actualDeptTime, short actualStoppageTime, short vehiclePosition, short recordStatus, Date lastModifiedTime, String lastModifiedUser) {
        this.id = id;
        this.stationType = stationType;
        this.tripReceiverId = tripReceiverId;
        this.definedArrivalTime = definedArrivalTime;
        this.definedDeptTime = definedDeptTime;
        this.definedStoppageTime = definedStoppageTime;
        this.actualArrivalTime = actualArrivalTime;
        this.actualDeptTime = actualDeptTime;
        this.actualStoppageTime = actualStoppageTime;
        this.vehiclePosition = vehiclePosition;
        this.recordStatus = recordStatus;
        this.lastModifiedTime = lastModifiedTime;
        this.lastModifiedUser = lastModifiedUser;
    }
    public OrTripStationsNew(OrTripStationsNewId id, String stationType, int tripReceiverId, Date definedArrivalTime, Date definedDeptTime, short definedStoppageTime, Date actualArrivalTime, Date actualDeptTime, short actualStoppageTime, short vehiclePosition, short recordStatus, Date lastModifiedTime, String lastModifiedUser, Date manualIn, Date manualOut, Short manualStoppageTime, Short manualVehiclePosition, Integer manualInLatitude, Integer manualInLongitude, Integer manualOutLatitude, Integer manualOutLongitude, Boolean manualEntryWarningSent, Boolean manualEntryOverrideFlag, Integer radius, Boolean insideRadius, Boolean podflag, String contactName, String emailId, String countryCode, String contactNumber) {
       this.id = id;
       this.stationType = stationType;
       this.tripReceiverId = tripReceiverId;
       this.definedArrivalTime = definedArrivalTime;
       this.definedDeptTime = definedDeptTime;
       this.definedStoppageTime = definedStoppageTime;
       this.actualArrivalTime = actualArrivalTime;
       this.actualDeptTime = actualDeptTime;
       this.actualStoppageTime = actualStoppageTime;
       this.vehiclePosition = vehiclePosition;
       this.recordStatus = recordStatus;
       this.lastModifiedTime = lastModifiedTime;
       this.lastModifiedUser = lastModifiedUser;
       this.manualIn = manualIn;
       this.manualOut = manualOut;
       this.manualStoppageTime = manualStoppageTime;
       this.manualVehiclePosition = manualVehiclePosition;
       this.manualInLatitude = manualInLatitude;
       this.manualInLongitude = manualInLongitude;
       this.manualOutLatitude = manualOutLatitude;
       this.manualOutLongitude = manualOutLongitude;
       this.manualEntryWarningSent = manualEntryWarningSent;
       this.manualEntryOverrideFlag = manualEntryOverrideFlag;
       this.radius = radius;
       this.insideRadius = insideRadius;
       this.podflag = podflag;
       this.contactName = contactName;
       this.emailId = emailId;
       this.countryCode = countryCode;
       this.contactNumber = contactNumber;
    }
   
    public OrTripStationsNewId getId() {
        return this.id;
    }
    
    public void setId(OrTripStationsNewId id) {
        this.id = id;
    }
    public String getStationType() {
        return this.stationType;
    }
    
    public void setStationType(String stationType) {
        this.stationType = stationType;
    }
    public int getTripReceiverId() {
        return this.tripReceiverId;
    }
    
    public void setTripReceiverId(int tripReceiverId) {
        this.tripReceiverId = tripReceiverId;
    }
    public Date getDefinedArrivalTime() {
        return this.definedArrivalTime;
    }
    
    public void setDefinedArrivalTime(Date definedArrivalTime) {
        this.definedArrivalTime = definedArrivalTime;
    }
    public Date getDefinedDeptTime() {
        return this.definedDeptTime;
    }
    
    public void setDefinedDeptTime(Date definedDeptTime) {
        this.definedDeptTime = definedDeptTime;
    }
    public short getDefinedStoppageTime() {
        return this.definedStoppageTime;
    }
    
    public void setDefinedStoppageTime(short definedStoppageTime) {
        this.definedStoppageTime = definedStoppageTime;
    }
    public Date getActualArrivalTime() {
        return this.actualArrivalTime;
    }
    
    public void setActualArrivalTime(Date actualArrivalTime) {
        this.actualArrivalTime = actualArrivalTime;
    }
    public Date getActualDeptTime() {
        return this.actualDeptTime;
    }
    
    public void setActualDeptTime(Date actualDeptTime) {
        this.actualDeptTime = actualDeptTime;
    }
    public short getActualStoppageTime() {
        return this.actualStoppageTime;
    }
    
    public void setActualStoppageTime(short actualStoppageTime) {
        this.actualStoppageTime = actualStoppageTime;
    }
    public short getVehiclePosition() {
        return this.vehiclePosition;
    }
    
    public void setVehiclePosition(short vehiclePosition) {
        this.vehiclePosition = vehiclePosition;
    }
    public short getRecordStatus() {
        return this.recordStatus;
    }
    
    public void setRecordStatus(short recordStatus) {
        this.recordStatus = recordStatus;
    }
    public Date getLastModifiedTime() {
        return this.lastModifiedTime;
    }
    
    public void setLastModifiedTime(Date lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }
    public String getLastModifiedUser() {
        return this.lastModifiedUser;
    }
    
    public void setLastModifiedUser(String lastModifiedUser) {
        this.lastModifiedUser = lastModifiedUser;
    }
    public Date getManualIn() {
        return this.manualIn;
    }
    
    public void setManualIn(Date manualIn) {
        this.manualIn = manualIn;
    }
    public Date getManualOut() {
        return this.manualOut;
    }
    
    public void setManualOut(Date manualOut) {
        this.manualOut = manualOut;
    }
    public Short getManualStoppageTime() {
        return this.manualStoppageTime;
    }
    
    public void setManualStoppageTime(Short manualStoppageTime) {
        this.manualStoppageTime = manualStoppageTime;
    }
    public Short getManualVehiclePosition() {
        return this.manualVehiclePosition;
    }
    
    public void setManualVehiclePosition(Short manualVehiclePosition) {
        this.manualVehiclePosition = manualVehiclePosition;
    }
    public Integer getManualInLatitude() {
        return this.manualInLatitude;
    }
    
    public void setManualInLatitude(Integer manualInLatitude) {
        this.manualInLatitude = manualInLatitude;
    }
    public Integer getManualInLongitude() {
        return this.manualInLongitude;
    }
    
    public void setManualInLongitude(Integer manualInLongitude) {
        this.manualInLongitude = manualInLongitude;
    }
    public Integer getManualOutLatitude() {
        return this.manualOutLatitude;
    }
    
    public void setManualOutLatitude(Integer manualOutLatitude) {
        this.manualOutLatitude = manualOutLatitude;
    }
    public Integer getManualOutLongitude() {
        return this.manualOutLongitude;
    }
    
    public void setManualOutLongitude(Integer manualOutLongitude) {
        this.manualOutLongitude = manualOutLongitude;
    }
    public Boolean getManualEntryWarningSent() {
        return this.manualEntryWarningSent;
    }
    
    public void setManualEntryWarningSent(Boolean manualEntryWarningSent) {
        this.manualEntryWarningSent = manualEntryWarningSent;
    }
    public Boolean getManualEntryOverrideFlag() {
        return this.manualEntryOverrideFlag;
    }
    
    public void setManualEntryOverrideFlag(Boolean manualEntryOverrideFlag) {
        this.manualEntryOverrideFlag = manualEntryOverrideFlag;
    }
    public Integer getRadius() {
        return this.radius;
    }
    
    public void setRadius(Integer radius) {
        this.radius = radius;
    }
    public Boolean getInsideRadius() {
        return this.insideRadius;
    }
    
    public void setInsideRadius(Boolean insideRadius) {
        this.insideRadius = insideRadius;
    }
    public Boolean getPodflag() {
        return this.podflag;
    }
    
    public void setPodflag(Boolean podflag) {
        this.podflag = podflag;
    }
    public String getContactName() {
        return this.contactName;
    }
    
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
    public String getContactNumber() {
        return this.contactNumber;
    }
    
    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }


	public Boolean getManualExitWarningSent() {
		return manualExitWarningSent;
	}


	public void setManualExitWarningSent(Boolean manualExitWarningSent) {
		this.manualExitWarningSent = manualExitWarningSent;
	}


	public Boolean getManualExitOverrideFlag() {
		return manualExitOverrideFlag;
	}


	public void setManualExitOverrideFlag(Boolean manualExitOverrideFlag) {
		this.manualExitOverrideFlag = manualExitOverrideFlag;
	}

	public String getSkipReason() {
		return skipReason;
	}
	public void setSkipReason(String skipReason) {
		this.skipReason = skipReason;
	}
}


