package com.claystone.db;

// Generated 18 Sep, 2012 9:30:02 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * OrWgUserAccess generated by hbm2java
 */
public class OrWgUserAccess implements java.io.Serializable {

	private OrWgUserAccessId id;
	private int groupOwnerId;
	private int lastModifiedUser;
	private Date lastModifiedTime;

	public OrWgUserAccess() {
	}

	public OrWgUserAccess(OrWgUserAccessId id, int groupOwnerId,
			int lastModifiedUser, Date lastModifiedTime) {
		this.id = id;
		this.groupOwnerId = groupOwnerId;
		this.lastModifiedUser = lastModifiedUser;
		this.lastModifiedTime = lastModifiedTime;
	}

	public OrWgUserAccessId getId() {
		return this.id;
	}

	public void setId(OrWgUserAccessId id) {
		this.id = id;
	}

	public int getGroupOwnerId() {
		return this.groupOwnerId;
	}

	public void setGroupOwnerId(int groupOwnerId) {
		this.groupOwnerId = groupOwnerId;
	}

	public int getLastModifiedUser() {
		return this.lastModifiedUser;
	}

	public void setLastModifiedUser(int lastModifiedUser) {
		this.lastModifiedUser = lastModifiedUser;
	}

	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

}
