package com.claystone.db;

// Generated 18 Sep, 2012 9:30:02 AM by Hibernate Tools 3.2.4.GA

/**
 * OrWgUserAccessId generated by hbm2java
 */
public class OrWgUserAccessId implements java.io.Serializable {

	private int userId;
	private int workgroupId;

	public OrWgUserAccessId() {
	}

	public OrWgUserAccessId(int userId, int workgroupId) {
		this.userId = userId;
		this.workgroupId = workgroupId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getWorkgroupId() {
		return this.workgroupId;
	}

	public void setWorkgroupId(int workgroupId) {
		this.workgroupId = workgroupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrWgUserAccessId))
			return false;
		OrWgUserAccessId castOther = (OrWgUserAccessId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getWorkgroupId() == castOther.getWorkgroupId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getWorkgroupId();
		return result;
	}

}
