package com.claystone.db;

// Generated 2 Jan, 2011 1:40:32 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * OrWorkgroupVehicle generated by hbm2java
 */
public class OrWorkgroupVehicle implements java.io.Serializable {

	private OrWorkgroupVehicleId id;
	private Date lastEffectiveDate;
	private short recordStatus;
	private Date lastModifiedTime;
	private String lastModifiedUser;

	public OrWorkgroupVehicle() {
	}

	public OrWorkgroupVehicle(OrWorkgroupVehicleId id, Date lastEffectiveDate,
			short recordStatus, Date lastModifiedTime, String lastModifiedUser) {
		this.id = id;
		this.lastEffectiveDate = lastEffectiveDate;
		this.recordStatus = recordStatus;
		this.lastModifiedTime = lastModifiedTime;
		this.lastModifiedUser = lastModifiedUser;
	}

	public OrWorkgroupVehicleId getId() {
		return this.id;
	}

	public void setId(OrWorkgroupVehicleId id) {
		this.id = id;
	}

	public Date getLastEffectiveDate() {
		return this.lastEffectiveDate;
	}

	public void setLastEffectiveDate(Date lastEffectiveDate) {
		this.lastEffectiveDate = lastEffectiveDate;
	}

	public short getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(short recordStatus) {
		this.recordStatus = recordStatus;
	}

	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	public String getLastModifiedUser() {
		return this.lastModifiedUser;
	}

	public void setLastModifiedUser(String lastModifiedUser) {
		this.lastModifiedUser = lastModifiedUser;
	}

}
