package com.claystone.db;

// Generated 2 Jan, 2011 1:40:32 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * OrWorkgroupVehicleId generated by hbm2java
 */
public class OrWorkgroupVehicleId implements java.io.Serializable {

	private int workgroupId;
	private int groupOwnerId;
	private int vehicleId;
	private int vehicleCompanyId;
	private Date firstEffectiveDate;

	public OrWorkgroupVehicleId() {
	}

	public OrWorkgroupVehicleId(int workgroupId, int groupOwnerId,
			int vehicleId, int vehicleCompanyId, Date firstEffectiveDate) {
		this.workgroupId = workgroupId;
		this.groupOwnerId = groupOwnerId;
		this.vehicleId = vehicleId;
		this.vehicleCompanyId = vehicleCompanyId;
		this.firstEffectiveDate = firstEffectiveDate;
	}

	public int getWorkgroupId() {
		return this.workgroupId;
	}

	public void setWorkgroupId(int workgroupId) {
		this.workgroupId = workgroupId;
	}

	public int getGroupOwnerId() {
		return this.groupOwnerId;
	}

	public void setGroupOwnerId(int groupOwnerId) {
		this.groupOwnerId = groupOwnerId;
	}

	public int getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(int vehicleId) {
		this.vehicleId = vehicleId;
	}

	public int getVehicleCompanyId() {
		return this.vehicleCompanyId;
	}

	public void setVehicleCompanyId(int vehicleCompanyId) {
		this.vehicleCompanyId = vehicleCompanyId;
	}

	public Date getFirstEffectiveDate() {
		return this.firstEffectiveDate;
	}

	public void setFirstEffectiveDate(Date firstEffectiveDate) {
		this.firstEffectiveDate = firstEffectiveDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrWorkgroupVehicleId))
			return false;
		OrWorkgroupVehicleId castOther = (OrWorkgroupVehicleId) other;

		return (this.getWorkgroupId() == castOther.getWorkgroupId())
				&& (this.getGroupOwnerId() == castOther.getGroupOwnerId())
				&& (this.getVehicleId() == castOther.getVehicleId())
				&& (this.getVehicleCompanyId() == castOther
						.getVehicleCompanyId())
				&& ((this.getFirstEffectiveDate() == castOther
						.getFirstEffectiveDate()) || (this
						.getFirstEffectiveDate() != null
						&& castOther.getFirstEffectiveDate() != null && this
						.getFirstEffectiveDate().equals(
								castOther.getFirstEffectiveDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getWorkgroupId();
		result = 37 * result + this.getGroupOwnerId();
		result = 37 * result + this.getVehicleId();
		result = 37 * result + this.getVehicleCompanyId();
		result = 37
				* result
				+ (getFirstEffectiveDate() == null ? 0 : this
						.getFirstEffectiveDate().hashCode());
		return result;
	}

}
