package com.claystone.db;

// Generated 2 Jan, 2011 10:07:52 PM by Hibernate Tools 3.2.4.GA

/**
 * OrWorkgroupId generated by hbm2java
 */
public class OrWorkgroupId implements java.io.Serializable {

	private int workgroupId;
	private int groupOwnerId;

	public OrWorkgroupId() {
	}

	public OrWorkgroupId(int workgroupId, int groupOwnerId) {
		this.workgroupId = workgroupId;
		this.groupOwnerId = groupOwnerId;
	}

	public int getWorkgroupId() {
		return this.workgroupId;
	}

	public void setWorkgroupId(int workgroupId) {
		this.workgroupId = workgroupId;
	}

	public int getGroupOwnerId() {
		return this.groupOwnerId;
	}

	public void setGroupOwnerId(int groupOwnerId) {
		this.groupOwnerId = groupOwnerId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrWorkgroupId))
			return false;
		OrWorkgroupId castOther = (OrWorkgroupId) other;

		return (this.getWorkgroupId() == castOther.getWorkgroupId())
				&& (this.getGroupOwnerId() == castOther.getGroupOwnerId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getWorkgroupId();
		result = 37 * result + this.getGroupOwnerId();
		return result;
	}

}
