package com.claystone.db;

// Generated 2 Jan, 2011 10:07:52 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * OrWorkgroup generated by hbm2java
 */
public class OrWorkgroup implements java.io.Serializable {

	private OrWorkgroupId id;
	private String workgroupName;
	private Date lastModifiedTime;
	private String lastModifiedUser;

	public OrWorkgroup() {
	}

	public OrWorkgroup(OrWorkgroupId id, String workgroupName,
			Date lastModifiedTime, String lastModifiedUser) {
		this.id = id;
		this.workgroupName = workgroupName;
		this.lastModifiedTime = lastModifiedTime;
		this.lastModifiedUser = lastModifiedUser;
	}

	public OrWorkgroupId getId() {
		return this.id;
	}

	public void setId(OrWorkgroupId id) {
		this.id = id;
	}

	public String getWorkgroupName() {
		return this.workgroupName;
	}

	public void setWorkgroupName(String workgroupName) {
		this.workgroupName = workgroupName;
	}

	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	public String getLastModifiedUser() {
		return this.lastModifiedUser;
	}

	public void setLastModifiedUser(String lastModifiedUser) {
		this.lastModifiedUser = lastModifiedUser;
	}

}
