package com.claystone.db;
// Generated 4 Jun, 2010 12:31:36 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * UsersId generated by hbm2java
 */
public class UsersId implements java.io.Serializable {

	private int userId;
	private int companyId;
	private short userLevel;
	private String userLoginName;
	private String userPassword;
	private Date lastLoginTime;
	private Date lastModifiedTime;
	private String lastModifiedUser;
	private int recordStatus;

	public UsersId() {
	}

	public UsersId(int userId, int companyId, short userLevel,
			String userLoginName, String userPassword, Date lastModifiedTime,
			String lastModifiedUser, int recordStatus) {
		this.userId = userId;
		this.companyId = companyId;
		this.userLevel = userLevel;
		this.userLoginName = userLoginName;
		this.userPassword = userPassword;
		this.lastModifiedTime = lastModifiedTime;
		this.lastModifiedUser = lastModifiedUser;
		this.recordStatus = recordStatus;
	}

	public UsersId(int userId, int companyId, short userLevel,
			String userLoginName, String userPassword, Date lastLoginTime,
			Date lastModifiedTime, String lastModifiedUser, int recordStatus) {
		this.userId = userId;
		this.companyId = companyId;
		this.userLevel = userLevel;
		this.userLoginName = userLoginName;
		this.userPassword = userPassword;
		this.lastLoginTime = lastLoginTime;
		this.lastModifiedTime = lastModifiedTime;
		this.lastModifiedUser = lastModifiedUser;
		this.recordStatus = recordStatus;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public short getUserLevel() {
		return this.userLevel;
	}

	public void setUserLevel(short userLevel) {
		this.userLevel = userLevel;
	}

	public String getUserLoginName() {
		return this.userLoginName;
	}

	public void setUserLoginName(String userLoginName) {
		this.userLoginName = userLoginName;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public Date getLastLoginTime() {
		return this.lastLoginTime;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	public String getLastModifiedUser() {
		return this.lastModifiedUser;
	}

	public void setLastModifiedUser(String lastModifiedUser) {
		this.lastModifiedUser = lastModifiedUser;
	}

	public int getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(int recordStatus) {
		this.recordStatus = recordStatus;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsersId))
			return false;
		UsersId castOther = (UsersId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getCompanyId() == castOther.getCompanyId())
				&& (this.getUserLevel() == castOther.getUserLevel())
				&& ((this.getUserLoginName() == castOther.getUserLoginName()) || (this
						.getUserLoginName() != null
						&& castOther.getUserLoginName() != null && this
						.getUserLoginName()
						.equals(castOther.getUserLoginName())))
				&& ((this.getUserPassword() == castOther.getUserPassword()) || (this
						.getUserPassword() != null
						&& castOther.getUserPassword() != null && this
						.getUserPassword().equals(castOther.getUserPassword())))
				&& ((this.getLastLoginTime() == castOther.getLastLoginTime()) || (this
						.getLastLoginTime() != null
						&& castOther.getLastLoginTime() != null && this
						.getLastLoginTime()
						.equals(castOther.getLastLoginTime())))
				&& ((this.getLastModifiedTime() == castOther
						.getLastModifiedTime()) || (this.getLastModifiedTime() != null
						&& castOther.getLastModifiedTime() != null && this
						.getLastModifiedTime().equals(
								castOther.getLastModifiedTime())))
				&& ((this.getLastModifiedUser() == castOther
						.getLastModifiedUser()) || (this.getLastModifiedUser() != null
						&& castOther.getLastModifiedUser() != null && this
						.getLastModifiedUser().equals(
								castOther.getLastModifiedUser())))
				&& (this.getRecordStatus() == castOther.getRecordStatus());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getCompanyId();
		result = 37 * result + this.getUserLevel();
		result = 37
				* result
				+ (getUserLoginName() == null ? 0 : this.getUserLoginName()
						.hashCode());
		result = 37
				* result
				+ (getUserPassword() == null ? 0 : this.getUserPassword()
						.hashCode());
		result = 37
				* result
				+ (getLastLoginTime() == null ? 0 : this.getLastLoginTime()
						.hashCode());
		result = 37
				* result
				+ (getLastModifiedTime() == null ? 0 : this
						.getLastModifiedTime().hashCode());
		result = 37
				* result
				+ (getLastModifiedUser() == null ? 0 : this
						.getLastModifiedUser().hashCode());
		result = 37 * result + this.getRecordStatus();
		return result;
	}

}
