package com.claystone.db;

// Generated 09-Sep-2010 16:06:00 by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private int userId;
	private int companyId;
	private short userLevel;
	private String userLoginName;
	private String userPassword;
	private Date lastLoginTime;
	private Date lastModifiedTime;
	private String lastModifiedUser;
	private int recordStatus;
	private String timezone;
	private String countryCode;
	private String mobileNumber;
	private String emailId;
	
	public Users() {
	}

	public Users(int userId, int companyId, short userLevel,
			String userLoginName, String userPassword, Date lastModifiedTime,
			String lastModifiedUser, int recordStatus, String timezone, String countryCode, String mobileNumber, 
			String emailId) {
		this.userId = userId;
		this.companyId = companyId;
		this.userLevel = userLevel;
		this.userLoginName = userLoginName;
		this.userPassword = userPassword;
		this.lastModifiedTime = lastModifiedTime;
		this.lastModifiedUser = lastModifiedUser;
		this.recordStatus = recordStatus;
		this.timezone = timezone;
		this.countryCode = countryCode;
		this.mobileNumber = mobileNumber;
		this.emailId = emailId;
	}

	public Users(int userId, int companyId, short userLevel,
			String userLoginName, String userPassword, Date lastLoginTime,
			Date lastModifiedTime, String lastModifiedUser, int recordStatus,
			String timezone, String countryCode,String mobileNumber,String emailId) {
		this.userId = userId;
		this.companyId = companyId;
		this.userLevel = userLevel;
		this.userLoginName = userLoginName;
		this.userPassword = userPassword;
		this.lastLoginTime = lastLoginTime;
		this.lastModifiedTime = lastModifiedTime;
		this.lastModifiedUser = lastModifiedUser;
		this.recordStatus = recordStatus;
		this.timezone = timezone;
		this.countryCode = countryCode;
		this.mobileNumber = mobileNumber;
		this.emailId = emailId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public short getUserLevel() {
		return this.userLevel;
	}

	public void setUserLevel(short userLevel) {
		this.userLevel = userLevel;
	}

	public String getUserLoginName() {
		return this.userLoginName;
	}

	public void setUserLoginName(String userLoginName) {
		this.userLoginName = userLoginName;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public Date getLastLoginTime() {
		return this.lastLoginTime;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	public String getLastModifiedUser() {
		return this.lastModifiedUser;
	}

	public void setLastModifiedUser(String lastModifiedUser) {
		this.lastModifiedUser = lastModifiedUser;
	}

	public int getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(int recordStatus) {
		this.recordStatus = recordStatus;
	}

	public String getTimezone() {
		return this.timezone;
	}

	public void setTimezone(String timezone) {
		this.timezone = timezone;
	}

	public String getCountryCode() {
		return countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}
	public String getMobileNumber() {
		return mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	public String getEmailId() {
		return emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

}
