package com.claystone.db; import java.util.Date;

import net.sf.gilead.pojo.java5.LightEntity;

/**
 * VehicleMobileUnitId generated by hbm2java
 */
public class VehicleMobileUnitId extends LightEntity implements java.io.Serializable {

	// Fields    

	/**
	 * 
	 */
	private static final long serialVersionUID = -449223905240895188L;

	private String mobileunitid;

	private int vehicleId;

	private Date firstEffectiveDate;

	// Constructors

	/** default constructor */
	public VehicleMobileUnitId() {
	}

	/** full constructor */
	public VehicleMobileUnitId(String mobileunitid, int vehicleId,
			Date firstEffectiveDate) {
		this.mobileunitid = mobileunitid;
		this.vehicleId = vehicleId;
		this.firstEffectiveDate = firstEffectiveDate;
	}

	// Property accessors
	public String getMobileunitid() {
		return this.mobileunitid;
	}

	public void setMobileunitid(String mobileunitid) {
		this.mobileunitid = mobileunitid;
	}

	public int getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(int vehicleId) {
		this.vehicleId = vehicleId;
	}

	public Date getFirstEffectiveDate() {
		return this.firstEffectiveDate;
	}

	public void setFirstEffectiveDate(Date firstEffectiveDate) {
		this.firstEffectiveDate = firstEffectiveDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VehicleMobileUnitId))
			return false;
		VehicleMobileUnitId castOther = (VehicleMobileUnitId) other;

		return ((this.getMobileunitid() == castOther.getMobileunitid()) || (this
				.getMobileunitid() != null
				&& castOther.getMobileunitid() != null && this
				.getMobileunitid().equals(castOther.getMobileunitid())))
				&& (this.getVehicleId() == castOther.getVehicleId())
				&& ((this.getFirstEffectiveDate() == castOther
						.getFirstEffectiveDate()) || (this
						.getFirstEffectiveDate() != null
						&& castOther.getFirstEffectiveDate() != null && this
						.getFirstEffectiveDate().equals(
								castOther.getFirstEffectiveDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getMobileunitid() == null ? 0 : this.getMobileunitid()
						.hashCode());
		result = 37 * result + this.getVehicleId();
		result = 37
				* result
				+ (getFirstEffectiveDate() == null ? 0 : this
						.getFirstEffectiveDate().hashCode());
		return result;
	}

}
