package com.claystone.db;
// Generated 28 Oct, 2021 10:58:23 AM by Hibernate Tools 3.5.0.Final

/**
 * VehicleId generated by hbm2java
 */
public class VehicleId implements java.io.Serializable {

	private int vehicleId;
	private int companyId;

	public VehicleId() {
	}

	public VehicleId(int vehicleId, int companyId) {
		this.vehicleId = vehicleId;
		this.companyId = companyId;
	}

	public int getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(int vehicleId) {
		this.vehicleId = vehicleId;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VehicleId))
			return false;
		VehicleId castOther = (VehicleId) other;

		return (this.getVehicleId() == castOther.getVehicleId()) && (this.getCompanyId() == castOther.getCompanyId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getVehicleId();
		result = 37 * result + this.getCompanyId();
		return result;
	}

}
