package com.claystone.db;
// Generated 4 Jun, 2010 12:56:15 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * VehicleMobileUnit generated by hbm2java
 */
public class VehicleMobileUnit implements java.io.Serializable {

	private VehicleMobileUnitId id;
	private Date lastEffectiveDate;
	private int companyId;
	private String input1;
	private String input2;
	private String input3;
	private String input4;
	private String adc1;
	private String adc2;
	private String adc1Class;
	private String adc2Class;
	private String output1;
	private String output2;
	private String output3;
	private String output4 = "Server3";
	private short speedLimit;
	private short idleTime;
	private Date lastModifiedTime;
	private String lastModifiedUser;
	private int distanceEventMeter;
	private boolean adc1Enabled;
	private boolean adc2Enabled;
	private Double adc1Ref1;
	private Double adc1Ref2;
	private Double adc1Ref3;
	private Double adc2Ref1;
	private Double adc2Ref2;
	private Double adc2Ref3;
	private Short adc1Limit;
	private Short adc2Limit;
	private boolean isActive;

	public VehicleMobileUnit() {
	}

	public VehicleMobileUnit(VehicleMobileUnitId id, Date lastEffectiveDate,
			int companyId, short speedLimit, short idleTime,
			Date lastModifiedTime, String lastModifiedUser,
			int distanceEventMeter, boolean adc1Enabled, boolean adc2Enabled) {
		this.id = id;
		this.lastEffectiveDate = lastEffectiveDate;
		this.companyId = companyId;
		this.speedLimit = speedLimit;
		this.idleTime = idleTime;
		this.lastModifiedTime = lastModifiedTime;
		this.lastModifiedUser = lastModifiedUser;
		this.distanceEventMeter = distanceEventMeter;
		this.adc1Enabled = adc1Enabled;
		this.adc2Enabled = adc2Enabled;
	}

	public VehicleMobileUnit(VehicleMobileUnitId id, Date lastEffectiveDate,
			int companyId, String input1, String input2, String input3,
			String input4, String adc1, String adc2, String adc1Class,
			String adc2Class, String output1, String output2, String output3,
			String output4, short speedLimit, short idleTime,
			Date lastModifiedTime, String lastModifiedUser,
			int distanceEventMeter, boolean adc1Enabled, boolean adc2Enabled,
			Double adc1Ref1, Double adc1Ref2, Double adc1Ref3, Double adc2Ref1,
			Double adc2Ref2, Double adc2Ref3, Short adc1Limit, Short adc2Limit) {
		this.id = id;
		this.lastEffectiveDate = lastEffectiveDate;
		this.companyId = companyId;
		this.input1 = input1;
		this.input2 = input2;
		this.input3 = input3;
		this.input4 = input4;
		this.adc1 = adc1;
		this.adc2 = adc2;
		this.adc1Class = adc1Class;
		this.adc2Class = adc2Class;
		this.output1 = output1;
		this.output2 = output2;
		this.output3 = output3;
		this.output4 = output4;
		this.speedLimit = speedLimit;
		this.idleTime = idleTime;
		this.lastModifiedTime = lastModifiedTime;
		this.lastModifiedUser = lastModifiedUser;
		this.distanceEventMeter = distanceEventMeter;
		this.adc1Enabled = adc1Enabled;
		this.adc2Enabled = adc2Enabled;
		this.adc1Ref1 = adc1Ref1;
		this.adc1Ref2 = adc1Ref2;
		this.adc1Ref3 = adc1Ref3;
		this.adc2Ref1 = adc2Ref1;
		this.adc2Ref2 = adc2Ref2;
		this.adc2Ref3 = adc2Ref3;
		this.adc1Limit = adc1Limit;
		this.adc2Limit = adc2Limit;
	}

	public VehicleMobileUnitId getId() {
		return this.id;
	}

	public void setId(VehicleMobileUnitId id) {
		this.id = id;
	}

	public Date getLastEffectiveDate() {
		return this.lastEffectiveDate;
	}

	public void setLastEffectiveDate(Date lastEffectiveDate) {
		this.lastEffectiveDate = lastEffectiveDate;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public String getInput1() {
		return this.input1;
	}

	public void setInput1(String input1) {
		this.input1 = input1;
	}

	public String getInput2() {
		return this.input2;
	}

	public void setInput2(String input2) {
		this.input2 = input2;
	}

	public String getInput3() {
		return this.input3;
	}

	public void setInput3(String input3) {
		this.input3 = input3;
	}

	public String getInput4() {
		return this.input4;
	}

	public void setInput4(String input4) {
		this.input4 = input4;
	}

	public String getAdc1() {
		return this.adc1;
	}

	public void setAdc1(String adc1) {
		this.adc1 = adc1;
	}

	public String getAdc2() {
		return this.adc2;
	}

	public void setAdc2(String adc2) {
		this.adc2 = adc2;
	}

	public String getAdc1Class() {
		return this.adc1Class;
	}

	public void setAdc1Class(String adc1Class) {
		this.adc1Class = adc1Class;
	}

	public String getAdc2Class() {
		return this.adc2Class;
	}

	public void setAdc2Class(String adc2Class) {
		this.adc2Class = adc2Class;
	}

	public String getOutput1() {
		return this.output1;
	}

	public void setOutput1(String output1) {
		this.output1 = output1;
	}

	public String getOutput2() {
		return this.output2;
	}

	public void setOutput2(String output2) {
		this.output2 = output2;
	}

	public String getOutput3() {
		return this.output3;
	}

	public void setOutput3(String output3) {
		this.output3 = output3;
	}

	public String getOutput4() {
		return this.output4;
	}

	public void setOutput4(String output4) {
		this.output4 = output4;
	}

	public short getSpeedLimit() {
		return this.speedLimit;
	}

	public void setSpeedLimit(short speedLimit) {
		this.speedLimit = speedLimit;
	}

	public short getIdleTime() {
		return this.idleTime;
	}

	public void setIdleTime(short idleTime) {
		this.idleTime = idleTime;
	}

	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	public String getLastModifiedUser() {
		return this.lastModifiedUser;
	}

	public void setLastModifiedUser(String lastModifiedUser) {
		this.lastModifiedUser = lastModifiedUser;
	}

	public int getDistanceEventMeter() {
		return this.distanceEventMeter;
	}

	public void setDistanceEventMeter(int distanceEventMeter) {
		this.distanceEventMeter = distanceEventMeter;
	}

	public boolean isAdc1Enabled() {
		return this.adc1Enabled;
	}

	public void setAdc1Enabled(boolean adc1Enabled) {
		this.adc1Enabled = adc1Enabled;
	}

	public boolean isAdc2Enabled() {
		return this.adc2Enabled;
	}

	public void setAdc2Enabled(boolean adc2Enabled) {
		this.adc2Enabled = adc2Enabled;
	}

	public Double getAdc1Ref1() {
		return this.adc1Ref1;
	}

	public void setAdc1Ref1(Double adc1Ref1) {
		this.adc1Ref1 = adc1Ref1;
	}

	public Double getAdc1Ref2() {
		return this.adc1Ref2;
	}

	public void setAdc1Ref2(Double adc1Ref2) {
		this.adc1Ref2 = adc1Ref2;
	}

	public Double getAdc1Ref3() {
		return this.adc1Ref3;
	}

	public void setAdc1Ref3(Double adc1Ref3) {
		this.adc1Ref3 = adc1Ref3;
	}

	public Double getAdc2Ref1() {
		return this.adc2Ref1;
	}

	public void setAdc2Ref1(Double adc2Ref1) {
		this.adc2Ref1 = adc2Ref1;
	}

	public Double getAdc2Ref2() {
		return this.adc2Ref2;
	}

	public void setAdc2Ref2(Double adc2Ref2) {
		this.adc2Ref2 = adc2Ref2;
	}

	public Double getAdc2Ref3() {
		return this.adc2Ref3;
	}

	public void setAdc2Ref3(Double adc2Ref3) {
		this.adc2Ref3 = adc2Ref3;
	}

	public Short getAdc1Limit() {
		return this.adc1Limit;
	}

	public void setAdc1Limit(Short adc1Limit) {
		this.adc1Limit = adc1Limit;
	}

	public Short getAdc2Limit() {
		return this.adc2Limit;
	}

	public void setAdc2Limit(Short adc2Limit) {
		this.adc2Limit = adc2Limit;
	}

	public boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}


}
