package com.claystone.db;
// Generated 28 Oct, 2021 10:58:23 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Vehicle generated by hbm2java
 */
public class Vehicle implements java.io.Serializable {

	private VehicleId id;
	private String licensePlate;
	private String vehicleBrand;
	private String vehicleColour;
	private String vehicleModel;
	private String vehicleChassisNo;
	private Integer vehicleOilTankSize;
	private short vehicleBattNormal;
	private short vehicleBattStarted;
	private String vehicleImageUrl;
	private char vehicleStatus;
	private Date lastModifiedTime;
	private String lastModifiedUser;
	private short recordStatus;
	private String alertEmailId;
	private String alertMobileNo;
	private String transporterName;
	private Short smsLimit;
	private String vehicleTypeImage;
	private String vehicleNativeName;

	public Vehicle() {
	}

	public Vehicle(VehicleId id, String licensePlate, short vehicleBattNormal, short vehicleBattStarted,
			char vehicleStatus, Date lastModifiedTime, String lastModifiedUser, short recordStatus) {
		this.id = id;
		this.licensePlate = licensePlate;
		this.vehicleBattNormal = vehicleBattNormal;
		this.vehicleBattStarted = vehicleBattStarted;
		this.vehicleStatus = vehicleStatus;
		this.lastModifiedTime = lastModifiedTime;
		this.lastModifiedUser = lastModifiedUser;
		this.recordStatus = recordStatus;
	}

	public Vehicle(VehicleId id, String licensePlate, String vehicleBrand, String vehicleColour, String vehicleModel,
			String vehicleChassisNo, Integer vehicleOilTankSize, short vehicleBattNormal, short vehicleBattStarted,
			String vehicleImageUrl, char vehicleStatus, Date lastModifiedTime, String lastModifiedUser,
			short recordStatus, String alertEmailId, String alertMobileNo, String transporterName, Short smsLimit,
			String vehicleTypeImage, String vehicleNativeName) {
		this.id = id;
		this.licensePlate = licensePlate;
		this.vehicleBrand = vehicleBrand;
		this.vehicleColour = vehicleColour;
		this.vehicleModel = vehicleModel;
		this.vehicleChassisNo = vehicleChassisNo;
		this.vehicleOilTankSize = vehicleOilTankSize;
		this.vehicleBattNormal = vehicleBattNormal;
		this.vehicleBattStarted = vehicleBattStarted;
		this.vehicleImageUrl = vehicleImageUrl;
		this.vehicleStatus = vehicleStatus;
		this.lastModifiedTime = lastModifiedTime;
		this.lastModifiedUser = lastModifiedUser;
		this.recordStatus = recordStatus;
		this.alertEmailId = alertEmailId;
		this.alertMobileNo = alertMobileNo;
		this.transporterName = transporterName;
		this.smsLimit = smsLimit;
		this.vehicleTypeImage = vehicleTypeImage;
		this.vehicleNativeName = vehicleNativeName;
	}

	public VehicleId getId() {
		return this.id;
	}

	public void setId(VehicleId id) {
		this.id = id;
	}

	public String getLicensePlate() {
		return this.licensePlate;
	}

	public void setLicensePlate(String licensePlate) {
		this.licensePlate = licensePlate;
	}

	public String getVehicleBrand() {
		return this.vehicleBrand;
	}

	public void setVehicleBrand(String vehicleBrand) {
		this.vehicleBrand = vehicleBrand;
	}

	public String getVehicleColour() {
		return this.vehicleColour;
	}

	public void setVehicleColour(String vehicleColour) {
		this.vehicleColour = vehicleColour;
	}

	public String getVehicleModel() {
		return this.vehicleModel;
	}

	public void setVehicleModel(String vehicleModel) {
		this.vehicleModel = vehicleModel;
	}

	public String getVehicleChassisNo() {
		return this.vehicleChassisNo;
	}

	public void setVehicleChassisNo(String vehicleChassisNo) {
		this.vehicleChassisNo = vehicleChassisNo;
	}

	public Integer getVehicleOilTankSize() {
		return this.vehicleOilTankSize;
	}

	public void setVehicleOilTankSize(Integer vehicleOilTankSize) {
		this.vehicleOilTankSize = vehicleOilTankSize;
	}

	public short getVehicleBattNormal() {
		return this.vehicleBattNormal;
	}

	public void setVehicleBattNormal(short vehicleBattNormal) {
		this.vehicleBattNormal = vehicleBattNormal;
	}

	public short getVehicleBattStarted() {
		return this.vehicleBattStarted;
	}

	public void setVehicleBattStarted(short vehicleBattStarted) {
		this.vehicleBattStarted = vehicleBattStarted;
	}

	public String getVehicleImageUrl() {
		return this.vehicleImageUrl;
	}

	public void setVehicleImageUrl(String vehicleImageUrl) {
		this.vehicleImageUrl = vehicleImageUrl;
	}

	public char getVehicleStatus() {
		return this.vehicleStatus;
	}

	public void setVehicleStatus(char vehicleStatus) {
		this.vehicleStatus = vehicleStatus;
	}

	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	public String getLastModifiedUser() {
		return this.lastModifiedUser;
	}

	public void setLastModifiedUser(String lastModifiedUser) {
		this.lastModifiedUser = lastModifiedUser;
	}

	public short getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(short recordStatus) {
		this.recordStatus = recordStatus;
	}

	public String getAlertEmailId() {
		return this.alertEmailId;
	}

	public void setAlertEmailId(String alertEmailId) {
		this.alertEmailId = alertEmailId;
	}

	public String getAlertMobileNo() {
		return this.alertMobileNo;
	}

	public void setAlertMobileNo(String alertMobileNo) {
		this.alertMobileNo = alertMobileNo;
	}

	public String getTransporterName() {
		return this.transporterName;
	}

	public void setTransporterName(String transporterName) {
		this.transporterName = transporterName;
	}

	public Short getSmsLimit() {
		return this.smsLimit;
	}

	public void setSmsLimit(Short smsLimit) {
		this.smsLimit = smsLimit;
	}

	public String getVehicleTypeImage() {
		return this.vehicleTypeImage;
	}

	public void setVehicleTypeImage(String vehicleTypeImage) {
		this.vehicleTypeImage = vehicleTypeImage;
	}

	public String getVehicleNativeName() {
		return this.vehicleNativeName;
	}

	public void setVehicleNativeName(String vehicleNativeName) {
		this.vehicleNativeName = vehicleNativeName;
	}

}
